// STREAM NOTIFICATIONS - one provider-neutral event contract worn by four visual designs.
//
// A follower, member, donation, gift and raid are data, not states. The state machine only
// owns the shared lifecycle: hidden -> enter -> hold -> exit. queueNotification() is the
// integration seam for a future provider adapter, but this template needs no provider and
// remains fully operable through ordinary SPX fields and the generated control page.

import type { AnimData, AnimStep } from '../../blocks/animData';
import { definitionScriptBlock } from '../../model/spxDefinition';
import { resolveEasing } from '../../model/easings';
import type { SpxField, SpxTemplate } from '../../model/types';
import { resolveTokens } from '../../model/themeTokens';
import {
  paletteById,
  resolveOptions,
  type ResolvedOptions,
  type TemplateVariant,
  type WizardOptions,
} from '../../model/wizard';
import {
  baseSettings,
  computeScale,
  documentHtml,
  maxTextWidthCss,
  stageBoxCss,
  resetCanvasCss,
  resolveHeadingFont,
  rootVarsCss,
  setFieldValueJs,
  zoneCssText,
} from '../shared/base';
import { convertToDataRegion } from '../shared/standard';
import { stageFitRuntimeJs } from '../shared/stageFit';
import { presetById, type PresetConfig } from '../lowerThirds/animPresets';

export const EVENT_LINES = [
  { title: 'Event label', sample: 'NEW MEMBER' },
  { title: 'Actor', sample: 'NovaRider' },
  { title: 'Amount / count', sample: '12 MONTHS' },
  { title: 'Message', sample: 'Welcome back to the crew - thank you for the support.' },
];

export interface StreamNotificationDesign {
  /**
   * THE STAGE WIDTH, in px at 1080p: the room this graphic was drawn for (`stageBoxCss` in
   * shared/base.ts carries the whole contract).
   *
   * With one declared, the panel stops hugging the operator's text and the text lives inside
   * it instead - which is what a BOARD needs, because the same panel is on air with different
   * content all evening and an audience reads a graphic that re-sizes itself as a broken one.
   * The number holds a realistic worst case; shorter content leaves reserved room where the
   * anchor already reads.
   */
  stageWidth?: number;
  html: string;
  css: string;
  hasAccent: boolean;
}

interface StreamNotificationSpec {
  id: string;
  name: string;
  description: string;
  styleTag: TemplateVariant['styleTag'];
  paletteId: string;
  fontId: string;
  uicolor: string;
  animationPresets: TemplateVariant['animationPresets'];
  /** The room this card was drawn for, in px at 1080p - see StreamNotificationDesign. */
  stageWidth?: number;
  build(o: ResolvedOptions): StreamNotificationDesign;
}

function notificationFields(o: ResolvedOptions): SpxField[] {
  const text = EVENT_LINES.map((line, i): SpxField => ({
    field: `f${i}`,
    ftype: i === 3 ? 'textarea' : 'textfield',
    title: o.lines[i]?.title || line.title,
    value: o.lines[i]?.sample ?? line.sample,
  }));
  return [
    ...text,
    {
      field: 'f4',
      ftype: 'filelist',
      title: 'Avatar / icon',
      value: '',
      assetfolder: './images/',
      extension: 'png',
    },
  ];
}

/** Add the explicit Hold waypoint and the exit callback that advances the event FIFO. */
function withNotificationHold(ease: string) {
  return (data: AnimData): AnimData => {
    const steps = [...data.steps];
    const outAt = steps.length - 1;
    const hold: AnimStep = {
      name: 'Hold',
      duration: 0.01,
      ease,
      layers: {},
    };
    steps.splice(outAt, 0, hold);
    const out = steps[steps.length - 1];
    steps[steps.length - 1] = {
      ...out,
      calls: [
        ...(out.calls ?? []),
        { time: out.duration, call: 'notificationDidExit' },
      ],
    };
    return { ...data, steps };
  };
}

function notificationRuntime(name: string, animationBlock: string): string {
  return `// ${name} - generated by NoaCG Studio. SPX calls update(), play(), stop(), next().

${setFieldValueJs}

// update(data): write fields only. Data updates never change the machine state.
function update(data) {
  var fields = (typeof data === 'string') ? JSON.parse(data) : data;
  for (var key in fields) {
    if (!Object.prototype.hasOwnProperty.call(fields, key)) continue;
    var el = document.getElementById(key);
    if (el) setFieldValue(el, fields[key]);
  }
  // Designs on a stage hold their lines to the rows they were drawn for (no-op otherwise).
  if (typeof fitStagedText === 'function') fitStagedText();
}

// notificationQueue holds complete snapshots, not references to mutable provider payloads.
// queueNotification() accepts either f0..f4 or friendly eventLabel/actor/amount/message/avatar
// keys. It is intentionally provider-neutral and safe to call from any future local adapter.
var notificationQueue = [];
var notificationActive = false;

function notificationCurrentValue(id) {
  var el = document.getElementById(id);
  if (!el) return '';
  return el.tagName === 'IMG' ? (el.getAttribute('src') || '') : (el.textContent || '');
}

function notificationSnapshot(payload) {
  var input = (typeof payload === 'string') ? JSON.parse(payload) : (payload || {});
  function pick(id, friendly) {
    if (input[id] !== undefined && input[id] !== null) return String(input[id]);
    if (input[friendly] !== undefined && input[friendly] !== null) return String(input[friendly]);
    return notificationCurrentValue(id);
  }
  return {
    f0: pick('f0', 'eventLabel'),
    f1: pick('f1', 'actor'),
    f2: pick('f2', 'amount'),
    f3: pick('f3', 'message'),
    f4: pick('f4', 'avatar')
  };
}

function notificationStart(item) {
  notificationActive = true;
  update(item);
  play();
}

function queueNotification(payload) {
  var item = notificationSnapshot(payload);
  if (notificationActive) {
    notificationQueue.push(item);
    return notificationQueue.length;
  }
  notificationStart(item);
  return 0;
}

// Called only by the authored end of the Out timeline. Replay and SNAP settling suppress
// lifecycle calls, so neither can accidentally consume an item.
function notificationDidExit() {
  notificationActive = false;
  if (!notificationQueue.length) return;
  var item = notificationQueue.shift();
  gsap.delayedCall(0, function () { notificationStart(item); });
}

function play() {
  notificationActive = true;
  gsap.killTweensOf('*');
  buildInTimeline();
}

function stop() {
  gsap.killTweensOf('*');
  buildOutTimeline();
}

function next() {
  return (typeof revealNextStep === 'function') ? revealNextStep() : null;
}

${animationBlock}
`;
}

function assembleNotification(
  spec: StreamNotificationSpec,
  design: StreamNotificationDesign,
  o: ResolvedOptions,
): SpxTemplate {
  const font = resolveHeadingFont(o);
  const scale = computeScale(o);
  const fields = notificationFields(o);
  const settings = baseSettings({ name: spec.name, uicolor: spec.uicolor }, o, { steps: '2' });
  const html = documentHtml({
    title: spec.name,
    definitionBlock: definitionScriptBlock(settings, fields),
    body: `  <!-- One parameterized stream event: follower, member, donation, gift or raid. -->
  <div class="stream-notification">
${design.html}
  </div>`,
  });

  const css = `/* ${spec.name} - generated by NoaCG Studio. Edit freely: this file is yours. */

${rootVarsCss(o, font.stack, scale, {
    tokens: resolveTokens(spec.styleTag),
    consumerCss: design.css,
  })}

${font.face}

${resetCanvasCss(o.resolution)}

.stream-notification {
  position: absolute;              /* the whole notification follows the chosen safe-area anchor */
${zoneCssText(o.zone, o.nudge, o.resolution)}
  opacity: 0;                      /* hidden until the entrance state runs */
}

.stream-notification-box {
${
    design.stageWidth
      ? stageBoxCss(o.resolution, design.stageWidth, o.zone, 'the room this card was drawn for')
      : "  width: fit-content;              /* hug short labels and names */"
  }
  max-width: ${maxTextWidthCss(o.resolution, Math.round(o.resolution.width * 0.46))}; /* wrap before the safe edge */
  text-align: left;                /* event cards always read left-to-right */
  will-change: transform, opacity; /* the panel is the animated surface */
}

.stream-notification-mask {
  min-width: 0;                    /* let text shrink inside grid and flex layouts */
  overflow: hidden;                /* reveal motion stays inside the card */
}

.stream-notification-message {
  display: -webkit-box;            /* clamp unpredictable viewer messages */
  -webkit-box-orient: vertical;    /* stack the clamped lines vertically */
  -webkit-line-clamp: 2;           /* keep the event compact */
  line-clamp: 2;                   /* standard spelling */
  overflow: hidden;                /* hide text beyond the clamp */
  overflow-wrap: break-word;       /* unbroken handles never escape */
}

.stream-notification-avatar {
  position: relative;              /* owns the fallback mark and image */
  overflow: hidden;                /* crop uploaded avatars to the design shape */
  flex: none;                      /* preserve the authored avatar geometry */
}

.stream-notification-avatar img {
  width: 100%;                     /* fill the design-owned avatar frame */
  height: 100%;                    /* fill the design-owned avatar frame */
  object-fit: cover;               /* crop without distorting */
}

.stream-notification-avatar:not(.has-image) img {
  display: none;                   /* the fallback mark is visible when no asset is supplied */
}

.stream-notification-glyph {
  position: absolute;              /* centered fallback icon under the optional image */
  inset: 0;                        /* fill the avatar frame */
  display: grid;                   /* center the mark */
  place-items: center;             /* center the mark */
}

.stream-notification-avatar.has-image .stream-notification-glyph {
  display: none;                   /* uploaded artwork replaces the fallback mark */
}

${design.css}
`;

  const preset = presetById(o.animation.presetId);
  const ease = resolveEasing(o.animation.easing, preset.autoEase);
  const cfg: PresetConfig = {
    prefix: 'stream-notification',
    lineCount: 4,
    hasAccent: design.hasAccent,
    steps: false,
    speed: o.animation.speed,
    easeIn: ease.easeIn,
    easeOut: ease.easeOut,
  };
  const js = notificationRuntime(spec.name, preset.emit(cfg));
  // A staged card holds its lines to the rows it was drawn for; a hugging one emits nothing.
  const jsWithStage = design.stageWidth
    ? `${js}\n\n${stageFitRuntimeJs('stream-notification')}`
    : js;

  const template: SpxTemplate = {
    name: spec.name,
    type: 'stream-notification',
    resolution: o.resolution,
    fps: o.fps,
    html,
    css,
    js: jsWithStage,
    fields,
    settings,
    assets: [...o.importedImages, ...(o.customFont ? [o.customFont.asset] : [])],
    layers: [
      ...fields.slice(0, 4).map((field) => ({
        id: field.field,
        type: 'text' as const,
        label: field.title,
        fieldId: field.field,
        text: field.value,
        styles: {},
      })),
      { id: 'f4', type: 'image' as const, label: 'Avatar / icon', fieldId: 'f4', styles: {} },
    ],
  };
  return convertToDataRegion(template, withNotificationHold(ease.easeIn));
}

export function defineStreamNotification(spec: StreamNotificationSpec): TemplateVariant {
  const variant: TemplateVariant = {
    id: spec.id,
    category: 'stream-notification',
    name: spec.name,
    styleTag: spec.styleTag,
    description: spec.description,
    maxLines: EVENT_LINES.length,
    suggestedLines: EVENT_LINES,
    logo: 'optional',
    animationPresets: spec.animationPresets,
    defaultPalette: paletteById(spec.paletteId),
    defaultFontId: spec.fontId,
    defaultZone: 'bottom-left',
    create(options?: WizardOptions) {
      const o = resolveOptions(variant, options);
      // The spec carries the stage, because the shared builders behind `build` draw four
      // different cards and each was drawn for a different width.
      return assembleNotification(spec, { ...spec.build(o), stageWidth: spec.stageWidth }, o);
    },
  };
  return variant;
}
