// Infographic scaffolding. Infographics host TWO data shapes — a big stat callout
// (headline number + label) and a horizontal bar chart — so unlike the standard
// categories the DESIGN owns its SPX fields and may ship extra runtime JS:
//   - stat designs: plain fields written straight into #fN elements, no extra JS.
//   - bar designs: a rebuildInfographic() function (in runtimeExtraJs) re-renders the
//     bar rows from the field values, exactly like tickers re-render their items.
//
// Structure contract:
//   <div class="ig">                 root — zone positioned; opacity:0 until play()
//     <div class="ig-box">           the panel; presets reveal this
//       …design markup: stat value (#f0), labels, or #ig-bars with .ig-bar-fill rows…
//     </div>
//   </div>
//
// The runtime calls rebuildInfographic() ONLY if the design defined one — the scaffold
// itself never assumes which of the two shapes it is hosting.

import type { SpxField, SpxTemplate } from '../../model/types';
import { definitionScriptBlock } from '../../model/spxDefinition';
import { resolveEasing } from '../../model/easings';
import {
  resolveOptions,
  type ResolvedOptions,
  type TemplateVariant,
  type WizardOptions,
} from '../../model/wizard';
import {
  baseSettings,
  computeScale,
  documentHtml,
  resetCanvasCss,
  resolveHeadingFont,
  rootVarsCss,
  zoneCssText,
} from '../shared/base';
import type { PresetConfig } from '../lowerThirds/animPresets';
import { igPresetById } from './igPresets';

export interface IgDesign {
  /** Inner HTML of .ig — must contain .ig-box (stat markup or #ig-bars rows). */
  html: string;
  /** Variant CSS (panel, value, labels, bars). Colors via :root vars only. */
  css: string;
  /** The design's own SPX fields — infographics don't use the wizard's line editor. */
  fields: SpxField[];
  /** Extra runtime JS (bar designs define rebuildInfographic() here; stat designs pass ''). */
  runtimeExtraJs: string;
}

export interface IgMeta {
  name: string;
  description: string;
  /** SPX UI color label, "1".."7". */
  uicolor: string;
}

/** The infographic runtime: standard SPX entry points + the optional rebuild hook. */
function igRuntimeJs(name: string, animationBlock: string): string {
  return `// ${name} — generated by SPX GFX Builder. SPX calls update(), play(), stop(), next().

// update(data): SPX sends field values as JSON, e.g. {"f0":"87%","f1":"Task completion"}.
// Each value is written into the element whose id matches the field name (f0 -> id="f0").
// Bar designs define rebuildInfographic() (re-renders the bars from the field values);
// stat designs don't — so it is only called when it exists.
function update(data) {
  var fields = (typeof data === 'string') ? JSON.parse(data) : data;
  for (var key in fields) {
    var el = document.getElementById(key);
    if (el) {
      el.textContent = fields[key];  // plain-text write — operator input never runs as HTML
      // Keep an untouched copy of the value: animations rewrite textContent while they
      // run (count-up shows "0%", "43%"…), so presets read the real target from here.
      el.setAttribute('data-target', fields[key]);
    }
  }
  if (typeof rebuildInfographic === 'function') rebuildInfographic();
}

// The timeline currently on air. play()/stop() kill it before starting a new one —
// gsap.killTweensOf('*') only matches DOM elements, so it would MISS tweens that
// target plain objects (like count-up's counter) and an interrupted replay would
// leave the old tween running against the new one. Killing the whole timeline
// stops every tween it owns, whatever kind of target it has.
var activeTl = null;

// play(): take the infographic on air — rebuild (fresh values), then run the entrance.
function play() {
  if (activeTl) activeTl.kill();   // stop everything the previous timeline started
  if (typeof rebuildInfographic === 'function') rebuildInfographic();
  activeTl = buildInTimeline();
}

// stop(): take the infographic off air — run the exit timeline.
function stop() {
  if (activeTl) activeTl.kill();
  activeTl = buildOutTimeline();
}

// next(): infographics have no steps.
function next() {}

${animationBlock}
`;
}

/** Build the complete infographic SpxTemplate. */
export function assembleInfographic(meta: IgMeta, design: IgDesign, o: ResolvedOptions): SpxTemplate {
  const font = resolveHeadingFont(o); // imported font wins over the bundled set
  const scale = computeScale(o);
  // Infographics carry a value + label block (or a bar chart) — cap a bit wider than a strap.
  const maxTextWidth = Math.round(o.resolution.width * 0.55);

  const settings = baseSettings(meta, o, { steps: '1' }); // infographics have no steps

  const html = documentHtml({
    title: meta.name,
    definitionBlock: definitionScriptBlock(settings, design.fields),
    body: `  <!-- Infographic root — a data callout panel (stat or bar chart). -->
  <div class="ig">
${design.html}
  </div>`,
  });

  const css = `/* ${meta.name} — generated by SPX GFX Builder. Edit freely: this file is yours. */

${rootVarsCss(o, font.stack, scale)}

${font.face}

${resetCanvasCss(o.resolution)}

/* ── Root position (anchor zone) ── */
.ig {
  position: absolute;
${zoneCssText(o.zone, o.nudge, o.resolution)}
  opacity: 0;                      /* hidden until play() runs the entrance */
}

/* ── Auto-fit: the panel hugs its content and wraps instead of overflowing. ── */
.ig-box {
  width: fit-content;              /* the panel hugs the stat / chart */
  max-width: ${maxTextWidth}px;             /* never wider than this — text wraps instead */
  will-change: transform, opacity; /* hint the browser: this element animates */
}
.ig-mask {
  overflow: hidden;                /* lines animate in from behind this mask */
}
.ig-mask > span {
  display: inline-block;           /* so the line can move inside its mask */
  overflow-wrap: break-word;       /* break very long unbroken words */
  text-wrap: balance;              /* wrapped rows get even lengths */
}

/* ── Design ── */
${design.css}
`;

  const preset = igPresetById(o.animation.presetId);
  // 'auto' uses the preset's hand-tuned ease pair; a named easing preset overrides both phases.
  const ease = resolveEasing(o.animation.easing, preset.autoEase);
  const cfg: PresetConfig = {
    prefix: 'ig',
    lineCount: design.fields.length,
    hasAccent: false,
    steps: false, // infographics never step — the whole callout enters at once
    speed: o.animation.speed,
    easeIn: ease.easeIn,
    easeOut: ease.easeOut,
  };

  // The design's extra runtime (e.g. rebuildInfographic()) lives OUTSIDE the marked
  // ANIMATION region — before it — so the Animation panel can never rewrite it.
  const extra = design.runtimeExtraJs.trim();
  const js = igRuntimeJs(meta.name, extra === '' ? preset.emit(cfg) : `${extra}

${preset.emit(cfg)}`);

  return {
    name: meta.name,
    type: 'infographic',
    resolution: o.resolution,
    fps: o.fps,
    html,
    css,
    js,
    fields: design.fields,
    settings,
    assets: [...o.importedImages, ...(o.customFont ? [o.customFont.asset] : [])],
    layers: design.fields.map((f) => ({
      id: f.field,
      type: 'text' as const,
      label: f.title,
      fieldId: f.field,
      text: f.value,
      styles: {},
    })),
  };
}

/** The authoring API for infographic variant modules. */
export function defineInfographicVariant(
  spec: Omit<TemplateVariant, 'create'>,
  meta: IgMeta,
  buildDesign: (o: ResolvedOptions) => IgDesign,
): TemplateVariant {
  const variant: TemplateVariant = {
    ...spec,
    create(options?: WizardOptions) {
      const o = resolveOptions(variant, options);
      return assembleInfographic(meta, buildDesign(o), o);
    },
  };
  return variant;
}
