// Shared helpers for SPX exporters. Exporters transform the editor template into a packaged
// folder structure WITHOUT changing how the graphic behaves.

import type JSZip from 'jszip';
import gsapSource from '../assets/gsap.min.js?raw';
import { parseDataUrl } from '../assets/assetUtils';
import { FONT_LICENSE_NOTE } from '../model/fonts';
import type { SpxTemplate } from '../model/types';

/** Slug suitable for a folder/zip name. */
export function slug(name: string): string {
  return (
    name
      .trim()
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '_')
      .replace(/^_+|_+$/g, '') || 'spx_template'
  );
}

/**
 * Bundle any fonts the template references (url("fonts/<file>.woff2") in its CSS) into the zip.
 * The files live in public/fonts/ (served at /fonts/<file> in dev and production builds), so we
 * fetch them at export time and write them under fonts/ with the same relative path the CSS uses.
 */
async function addReferencedFonts(zip: JSZip, template: SpxTemplate): Promise<void> {
  const refs = [...template.css.matchAll(/url\(["']?fonts\/([\w.-]+\.(?:woff2|woff|ttf|otf))["']?\)/gi)].map((m) => m[1]);
  const unique = [...new Set(refs)];
  if (unique.length === 0) return;
  // Imported fonts already live in template.assets (written by the assets loop);
  // only the builder-bundled files need fetching from /fonts.
  const assetPaths = new Set(template.assets.map((a) => a.path));
  for (const file of unique) {
    if (assetPaths.has(`fonts/${file}`)) continue;
    try {
      const res = await fetch(`/fonts/${file}`);
      if (!res.ok) continue;
      zip.file(`fonts/${file}`, await res.arrayBuffer());
    } catch {
      // Font fetch failed (offline dev edge case) — the export still works with fallback fonts.
    }
  }
  zip.file('FONT_LICENSES.md', FONT_LICENSE_NOTE);
}

/** Write the bundled GSAP, fonts, and any template assets into the zip (relative paths). */
export async function addSharedAssets(zip: JSZip, template: SpxTemplate): Promise<void> {
  zip.file('js/gsap.min.js', gsapSource);
  await addReferencedFonts(zip, template);
  for (const asset of template.assets) {
    if (typeof asset.data === 'string') {
      const parsed = parseDataUrl(asset.data);
      if (parsed) {
        // Decode the base64 data URL back into a real binary file.
        zip.file(asset.path, parsed.base64, { base64: true });
      } else {
        // Plain text asset (e.g. a stylesheet or SVG source).
        zip.file(asset.path, asset.data);
      }
    } else {
      // A Blob.
      zip.file(asset.path, asset.data);
    }
  }
}

/** Ensure the HTML references the external css/js/gsap files (Starter packaging). */
export function ensureExternalRefs(html: string): string {
  let out = html;
  const head = /<\/head>/i;
  if (!/href=["'](?:\.\/)?css\/template\.css["']/i.test(out) && head.test(out)) {
    out = out.replace(head, `  <link rel="stylesheet" href="css/template.css" />\n</head>`);
  }
  if (!/src=["'](?:\.\/)?js\/gsap\.min\.js["']/i.test(out) && head.test(out)) {
    out = out.replace(head, `  <script src="js/gsap.min.js"></script>\n</head>`);
  }
  if (!/src=["'](?:\.\/)?js\/template\.js["']/i.test(out) && head.test(out)) {
    out = out.replace(head, `  <script src="js/template.js"></script>\n</head>`);
  }
  return out;
}

/** A short README explaining how to deploy the package in SPX. */
export function spxReadme(template: SpxTemplate, mode: string): string {
  return `# ${template.name} — SPX template (${mode})

Generated by SPX HTML GFX Builder.

## Install
Copy this folder into your SPX assets:

    ASSETS/templates/<company>/<project>/${slug(template.name)}/

Then select the template in an SPX rundown.

## Files
- index.html      The template (loads css/js below).
- css/template.css  Styles.
- js/template.js    Runtime: play(), stop(), update(data).
- js/gsap.min.js    Bundled GSAP animation library (no internet required).
${template.assets.length ? '- assets/...        Images / media used by the template.\n' : ''}
## Data fields
${template.fields.map((f) => `- ${f.field} (${f.ftype}): ${f.title}`).join('\n') || '- (none)'}

All paths are relative, so the package is plug-and-play.
`;
}
