// Shared helpers for SPX exporters. Exporters transform the editor template into a packaged
// folder structure WITHOUT changing how the graphic behaves.

import type JSZip from 'jszip';
import gsapSource from '../assets/gsap.min.js?raw';
import { parseDataUrl } from '../assets/assetUtils';
import { FONT_LICENSE_NOTE } from '../model/fonts';
import type { SpxTemplate } from '../model/types';
import { controlChannelName } from '../control/controlModel';
import { controlReceiverScript } from '../control/receiverScript';
import { renderControlPanelHtml } from '../control/controlPanelHtml';

export { slug } from './slug';
import { slug } from './slug';

/**
 * Bundle any fonts the template references (url("fonts/<file>.woff2") in its CSS) into the zip.
 * The files live in public/fonts/ (served at /fonts/<file> in dev and production builds), so we
 * fetch them at export time and write them under fonts/ with the same relative path the CSS uses.
 */
export async function addReferencedFonts(zip: JSZip, template: SpxTemplate): Promise<void> {
  const refs = [...template.css.matchAll(/url\(["']?fonts\/([\w.-]+\.(?:woff2|woff|ttf|otf))["']?\)/gi)].map((m) => m[1]);
  const unique = [...new Set(refs)];
  if (unique.length === 0) return;
  // Imported fonts already live in template.assets (written by the assets loop);
  // only the builder-bundled files need fetching from /fonts.
  const assetPaths = new Set(template.assets.map((a) => a.path));
  for (const file of unique) {
    if (assetPaths.has(`fonts/${file}`)) continue;
    try {
      const res = await fetch(`/fonts/${file}`);
      if (!res.ok) continue;
      zip.file(`fonts/${file}`, await res.arrayBuffer());
    } catch {
      // Font fetch failed (offline dev edge case) — the export still works with fallback fonts.
    }
  }
  zip.file('FONT_LICENSES.md', FONT_LICENSE_NOTE);
}

/** Write the bundled GSAP, fonts, and any template assets into the zip (relative paths). */
export async function addSharedAssets(zip: JSZip, template: SpxTemplate): Promise<void> {
  zip.file('js/gsap.min.js', gsapSource);
  await addReferencedFonts(zip, template);
  for (const asset of template.assets) {
    if (typeof asset.data === 'string') {
      const parsed = parseDataUrl(asset.data);
      if (parsed) {
        // Decode the base64 data URL back into a real binary file.
        zip.file(asset.path, parsed.base64, { base64: true });
      } else {
        // Plain text asset (e.g. a stylesheet or SVG source).
        zip.file(asset.path, asset.data);
      }
    } else {
      // A Blob.
      zip.file(asset.path, asset.data);
    }
  }
}

/** Ensure the HTML references the external css/js/gsap files (Starter packaging). */
export function ensureExternalRefs(html: string): string {
  let out = html;
  const head = /<\/head>/i;
  if (!/href=["'](?:\.\/)?css\/template\.css["']/i.test(out) && head.test(out)) {
    out = out.replace(head, `  <link rel="stylesheet" href="css/template.css" />\n</head>`);
  }
  if (!/src=["'](?:\.\/)?js\/gsap\.min\.js["']/i.test(out) && head.test(out)) {
    out = out.replace(head, `  <script src="js/gsap.min.js"></script>\n</head>`);
  }
  if (!/src=["'](?:\.\/)?js\/template\.js["']/i.test(out) && head.test(out)) {
    out = out.replace(head, `  <script src="js/template.js"></script>\n</head>`);
  }
  return out;
}

/**
 * Inject the control receiver before </body> so a standalone control panel on the same
 * machine can drive the graphic live (BroadcastChannel). SPX/CasparCG still call the
 * globals directly; this only adds a listener. No-op when there is no </body>.
 */
export function injectControlReceiver(html: string, template: SpxTemplate): string {
  const block = controlReceiverScript(template.name, controlChannelName(template.name));
  return /<\/body>/i.test(html) ? html.replace(/<\/body>/i, `${block}\n</body>`) : html + block;
}

/** Bundle the generated controlpanel.html next to the graphic. */
export function addControlPanel(root: JSZip, template: SpxTemplate): void {
  root.file('controlpanel.html', renderControlPanelHtml(template));
}

/** A short README explaining how to deploy the package in SPX. */
export function spxReadme(template: SpxTemplate, mode: string): string {
  return `# ${template.name} — SPX template (${mode})

Generated by SPX HTML GFX Builder.

## Install
Extract the zip into your SPX / CasparCG templates folder — it already contains the
project folder, so you get:

    [TemplatesFolder]/${slug(template.name)}/index.html
    [TemplatesFolder]/${slug(template.name)}/images/...

(For SPX that is typically ASSETS/templates/<company>/${slug(template.name)}/.)
Then select the template in an SPX rundown.

## Files
- index.html      The template (loads css/js below).
- css/template.css  Styles.
- js/template.js    Runtime: play(), stop(), update(data).
- js/gsap.min.js    Bundled GSAP animation library (no internet required).
${template.assets.length ? '- images/...        Images used by the template (image fields list this folder).\n' : ''}- controlpanel.html An operator page auto-built from the fields (see below).

## Data fields
${template.fields.map((f) => `- ${f.field} (${f.ftype}): ${f.title}`).join('\n') || '- (none)'}

## Operating it live (controlpanel.html)
Run index.html as a browser source (OBS, vMix, a browser tab), then open controlpanel.html
in another tab of the SAME browser. Edits and the Play/Stop/Update/Next buttons drive the
graphic live over a BroadcastChannel — no server needed. (In an SPX rundown you drive the
template the usual way; the control panel is an alternative for browser-source workflows.)

All paths are relative, so the package is plug-and-play.
`;
}
