// Shared helpers for SPX exporters. Exporters transform the editor template into a packaged
// folder structure WITHOUT changing how the graphic behaves.

import type JSZip from 'jszip';
import gsapSource from '../assets/gsap.min.js?raw';
import type { SpxTemplate } from '../model/types';

/** Slug suitable for a folder/zip name. */
export function slug(name: string): string {
  return (
    name
      .trim()
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '_')
      .replace(/^_+|_+$/g, '') || 'spx_template'
  );
}

/** Write the bundled GSAP and any template assets into the zip (relative paths). */
export async function addSharedAssets(zip: JSZip, template: SpxTemplate): Promise<void> {
  zip.file('js/gsap.min.js', gsapSource);
  for (const asset of template.assets) {
    zip.file(asset.path, asset.data as Blob | string);
  }
}

/** Ensure the HTML references the external css/js/gsap files (Starter packaging). */
export function ensureExternalRefs(html: string): string {
  let out = html;
  const head = /<\/head>/i;
  if (!/href=["'](?:\.\/)?css\/template\.css["']/i.test(out) && head.test(out)) {
    out = out.replace(head, `  <link rel="stylesheet" href="css/template.css" />\n</head>`);
  }
  if (!/src=["'](?:\.\/)?js\/gsap\.min\.js["']/i.test(out) && head.test(out)) {
    out = out.replace(head, `  <script src="js/gsap.min.js"></script>\n</head>`);
  }
  if (!/src=["'](?:\.\/)?js\/template\.js["']/i.test(out) && head.test(out)) {
    out = out.replace(head, `  <script src="js/template.js"></script>\n</head>`);
  }
  return out;
}

/** A short README explaining how to deploy the package in SPX. */
export function spxReadme(template: SpxTemplate, mode: string): string {
  return `# ${template.name} — SPX template (${mode})

Generated by SPX HTML GFX Builder.

## Install
Copy this folder into your SPX assets:

    ASSETS/templates/<company>/<project>/${slug(template.name)}/

Then select the template in an SPX rundown.

## Files
- index.html      The template (loads css/js below).
- css/template.css  Styles.
- js/template.js    Runtime: play(), stop(), update(data).
- js/gsap.min.js    Bundled GSAP animation library (no internet required).
${template.assets.length ? '- assets/...        Images / media used by the template.\n' : ''}
## Data fields
${template.fields.map((f) => `- ${f.field} (${f.ftype}): ${f.title}`).join('\n') || '- (none)'}

All paths are relative, so the package is plug-and-play.
`;
}
