// GETTING-ON-AIR.md — the playout-side quick guide bundled into exported packages.
// A condensed, package-local edition of docs/PLAYOUT_INTEGRATION.md, written for the person
// configuring the playout machine (who never sees this repo). Keep the two in agreement:
// anything corrected here is usually wrong in the doc too.
//
// THE GUIDE ONLY DESCRIBES WHAT IS IN THE FOLDER (student-release acceptance, 2026-08-05).
// One text served every flavour, so an SPX or CasparCG package — which carries no relay on
// purpose, because the playout host is the controller there — told its reader to double-click
// a "Start controller.cmd" that was never written into it. A guide that names a missing file
// is worse than one that says nothing: it reads as a broken export. `localController` is what
// the CALLER actually bundled (export/localControl.ts addLocalControlBundle), never a wish.

export interface OnAirGuideOptions {
  /** True only when addLocalControlBundle wrote the relay + launchers into THIS package. */
  localController?: boolean;
}

export function onAirGuideMd(opts?: OnAirGuideOptions): string {
  const localController = opts?.localController ?? false;
  return `# Getting this package on air

Generated by NoaCG Studio. Everything in this folder is self-contained — relative paths,
bundled fonts and GSAP, no internet needed to render.

## The three rules every browser playout shares

- **Transparency is built in.** Do not add a chroma key. A black/white box behind the graphic
  means the host is forcing an opaque background — clear its custom CSS/background setting.
- **Match the resolution exactly** (the README states this package's canvas). Set the browser
  source to the same numbers; resize the source, never the resulting layer.
- **Match the channel's frame rate** on the browser source.

## SPX Graphics

1. Extract this folder into SPX's \`ASSETS/templates/\` directory.
2. Add the template to a rundown — the operator fields come from the template's own definition.
3. **Play** airs it, **Continue** walks its steps, **Stop** plays it out.

## CasparCG

Use the HTML producer. For a folder package, point at the template's own .html file; a
single-file CasparCG export drops straight into the server's template folder:

    CG 1-20 ADD 1 "<template-name>" 1 "<templateData>...</templateData>"
    CG 1-20 PLAY

On CasparCG **2.3.x** the bundled browser is old (Chromium 6x): if you hand-edit template code,
avoid modern syntax like \`?.\` — a too-modern page dies silently with a SyntaxError only in the
server log. Generated code already respects that bar.

## OBS Studio / vMix

Add a **Browser** source (OBS) or **Web Browser** input (vMix), point it at the graphic's .html
file, set width/height to the graphic's resolution, leave the background alone.

## What the fields are called (FIELDS.md)

Every value this package can be given is listed in **FIELDS.md**, with the **ID** a playout
client sends it under — \`f0\`, \`f1\`, … That is the file to keep open beside a CasparCG client:
the client shows you ids, and FIELDS.md is what says which id is the title and which is the name.

${
  localController
    ? `## Local control — the launcher

This package bundles a tiny **local relay**: double-click **"Start controller.cmd"** (Windows)
or **"start-controller.command"** (macOS; Linux: \`./start-controller.sh\`). It serves this folder
at \`http://localhost:<port>/\`, opens the operator page, and relays every command through an
ordered log — which is the only route into a graphic loaded by OBS/vMix (they run their own
browser engine that a browser tab can never reach directly).

1. Start the launcher and keep its window open.
2. Point the OBS/vMix browser source at the graphic ON THAT ADDRESS
   (\`http://localhost:<port>/<graphic>.html\`), not at the file on disk.
3. Operate from the panel the launcher opened. Fully offline; no accounts, no internet.

macOS note: the .command file may need one-time permission (System Settings → Privacy &
Security), and python3 comes with the OS developer tools.

## The bundled control panel without the launcher

\`controlpanel.html\` can also drive a graphic over a **same-origin browser channel**:

- **Works:** both pages opened from the same web address (http:// or https://, same host and
  port) in the same browser — the launcher above, SPX's own template server, or any web server.
- **Does not work:** opening the files straight from disk (\`file://\`) — the browser gives every
  local file its own private origin, so the pages cannot see each other. The panel will tell you
  when nothing is answering.`
    : `## Steering these graphics

**The playout host is the controller for this package** — that is why there is no launcher and
no relay in this folder, and why nothing here fights the host for the graphic.

- **SPX:** the rundown. Fill the fields in SPX, then Play / Continue / Stop.
- **CasparCG:** your CasparCG client (the official CasparCG Client, CasparCG Media Scanner
  clients, Sofie, OpenPlayout…). It sends the field ids from **FIELDS.md**; \`CG ADD\` loads the
  template, \`CG PLAY\` airs it, \`CG NEXT\` steps it and \`CG STOP\` plays it out.
- **A double-click local operator page instead?** Export the same graphic (or the same
  production) as the **HTML overlay (OBS / vMix)** target. That package bundles a localhost
  relay and double-click launchers, and is the flavour meant for hosts that have no controller
  of their own. (The launcher filenames are named only in the packages that carry them, so a
  guide never sends you looking for a file that is not there.)

## The fallback: controlpanel.html

**\`controlpanel.html\` in this folder is for the day the playout host is not there** — the machine
did not come, the network died, the rundown is gone. It has every field and every button this
graphic declares, and it needs nothing but a browser.

It pairs only over a **same-origin browser channel**: both pages opened from ONE http(s) address
in ONE browser. So serve this folder over any local web server, open the graphic's own \`.html\`
in one tab and \`controlpanel.html\` in another, and drive it from there.

- Opening the files straight from disk (\`file://\`) never pairs — the browser gives every local
  file its own private origin. The panel says so rather than pretending.
- It can never reach a graphic loaded by OBS/vMix/CasparCG itself: those run their own browser
  engine. Under the host, use the host's controls above.`
}

## When it does not work

| Symptom | Usually means | Fix |
|---|---|---|
| Layer on air, nothing renders, no error | CasparCG 2.3.x rejected edited JS | Check server log for SyntaxError; remove \`?.\`/\`??\` |
| Black/white box behind the graphic | Host forcing opaque background | Clear custom CSS/background; no chroma key |
| Soft or wrong-sized graphic | Source dimensions do not match the design | Set the source to the graphic's own resolution |
| Control panel buttons do nothing | Pages not same-origin (file://, or different hosts) | Serve both over one http address, or use the host's own controls |
`;
}
