// Whole-packet export: one zip with every graphic of the packet as its own SPX Starter
// folder — extract into the templates folder and the show's full set is in place:
//   [TemplatesFolder]/<packet>/<graphic>/index.html + css/ js/ images/ fonts/

import JSZip from 'jszip';
import { slug } from './common';
import { buildStarterInto } from './targets/spxStarter';
import type { Packet } from '../model/packets';

export async function buildPacketZip(packet: Packet): Promise<JSZip> {
  const zip = new JSZip();
  const root = zip.folder(slug(packet.name))!;
  const used = new Set<string>();
  for (const graphic of packet.graphics) {
    // Two graphics can slug identically ("Ticker" / "ticker!") — suffix the collision.
    let name = slug(graphic.name);
    let n = 2;
    while (used.has(name)) name = `${slug(graphic.name)}_${n++}`;
    used.add(name);
    await buildStarterInto(root.folder(name)!, graphic.template);
  }
  root.file(
    'README.md',
    `# ${packet.name} — broadcast packet\n\nGenerated by SPX HTML GFX Builder.\n\n` +
      `Each folder is one plug-and-play SPX template:\n\n` +
      packet.graphics.map((g) => `- ${slug(g.name)}/  (${g.type})`).join('\n') +
      `\n\nExtract this folder into your SPX/CasparCG templates directory as-is.\n`,
  );
  return zip;
}
