// Whole-package export: one zip with every graphic of a package as its own SPX Starter
// folder — extract into the templates folder and the show's full set is in place:
//   [TemplatesFolder]/<package>/<graphic>/index.html + css/ js/ images/ fonts/
//
// The caller resolves the package's graphics from the library (docs/SAVED_CONTENT_MODEL.md);
// this module only needs names + templates, so it serves packages, ad-hoc selections, and
// tests alike.

import JSZip from 'jszip';
import { slug } from './common';
import { buildStarterInto } from './targets/spxStarter';
import type { SpxTemplate } from '../model/types';
import type { ControlEntry } from '../model/library';

export interface ExportableGraphic {
  name: string;
  template: SpxTemplate;
  /** The graphic's saved control-panel entries, baked into its bundled operator page. The
   *  caller already holds the library records here, so there is nothing to resolve. */
  entries?: ControlEntry[];
}

export async function buildGraphicsZip(packageName: string, graphics: ExportableGraphic[]): Promise<JSZip> {
  const zip = new JSZip();
  const root = zip.folder(slug(packageName))!;
  const used = new Set<string>();
  for (const graphic of graphics) {
    // Two graphics can slug identically ("Ticker" / "ticker!") — suffix the collision.
    let name = slug(graphic.name);
    let n = 2;
    while (used.has(name)) name = `${slug(graphic.name)}_${n++}`;
    used.add(name);
    await buildStarterInto(root.folder(name)!, graphic.template, { entries: graphic.entries });
  }
  root.file(
    'README.md',
    `# ${packageName} — broadcast package\n\nGenerated by NoaCG Studio.\n\n` +
      `Each folder is one plug-and-play SPX template:\n\n` +
      graphics.map((g) => `- ${slug(g.name)}/  (${g.template.type})`).join('\n') +
      `\n\nExtract this folder into your SPX/CasparCG templates directory as-is.\n`,
  );
  return zip;
}
