// Whole-show export (Phase 5): one zip with every graphic of the show as its own SPX
// Starter folder PLUS one aggregated show_controlpanel.html at the root — the show's
// control page, generated from every graphic's fields and state machine. Run each
// graphic's index.html as a browser source and open the show panel in the same browser:
// every card drives its graphic over that graphic's own BroadcastChannel.
//
// Each graphic's saved control-panel ENTRIES live in the library, not in the show's embedded
// copy — they are resolved out of the library at export time (entriesForSavedGraphic, by
// graphicId with a unique-name fallback, the same resolver the hosted control page uses) and
// baked into both the aggregated panel and each graphic's own controlpanel.html.
//
//   <show>/show_controlpanel.html
//   <show>/<graphic>/index.html + css/ js/ images/ fonts/ + controlpanel.html

import JSZip from 'jszip';
import { slug } from './common';
import { buildStarterInto } from './targets/spxStarter';
import { renderShowControlPanelHtml } from '../control/controlPanelHtml';
import { hostedReceiverConfig, hostedReceiverBlock, stripHostedReceiver } from '../control/hostedReceiver';
import { loadGraphics, entriesForSavedGraphic, templateForSavedGraphic } from '../model/library';
import type { Show } from '../model/shows';

/** Optional seam for the hosted receiver's backend coordinates. Defaults to the app's own
 *  configured backend (control/hostedReceiver.ts); the offline e2e suite — which builds with
 *  no backend env at all — passes explicit coordinates to exercise the injection. */
export interface ShowExportOptions {
  hostedBackend?: { ref: string; key: string } | null;
}

export async function buildShowZip(show: Show, opts?: ShowExportOptions): Promise<JSZip> {
  const zip = new JSZip();
  const root = zip.folder(slug(show.name))!;
  // Each graphic's saved control-panel entries live in the library, not in the show's embedded
  // copy — resolve them once here (by graphicId, unique-name fallback) so both the aggregated
  // show panel and each graphic's own controlpanel.html bake them in. Authoring stays in the
  // app; a change reaches the package on the next export (docs/SAVED_CONTENT_MODEL.md §4).
  const library = loadGraphics();
  const used = new Set<string>();
  for (const graphic of show.graphics) {
    // Two graphics can slug identically ("Ticker" / "ticker!") — suffix the collision.
    let name = slug(graphic.name);
    let n = 2;
    while (used.has(name)) name = `${slug(graphic.name)}_${n++}`;
    used.add(name);
    // A published show bakes the hosted-control receiver into each graphic, so the exported
    // package is drivable from the hosted page as-is. The saved snapshot stays clean — the
    // block exists only in the export; an unpublished show exports 100% offline.
    // The LIVE template from the library (templateForSavedGraphic), not the snapshot embedded
    // when the graphic was added — the graphic keeps being edited, and the export must ship
    // what it looks like now.
    let template = templateForSavedGraphic(graphic, library);
    const hosted = show.hostedSlug
      ? opts?.hostedBackend
        ? { ...opts.hostedBackend, slug: show.hostedSlug, graphic: graphic.name }
        : hostedReceiverConfig(show.hostedSlug, graphic.name)
      : null;
    if (hosted) {
      const js = stripHostedReceiver(template.js).trimEnd() + '\n\n' + hostedReceiverBlock(hosted);
      template = { ...template, js };
    }
    await buildStarterInto(root.folder(name)!, template, { entries: entriesForSavedGraphic(graphic, library) });
  }
  root.file(
    'show_controlpanel.html',
    renderShowControlPanelHtml(
      show.name,
      show.graphics.map((g) => ({ template: templateForSavedGraphic(g, library), entries: entriesForSavedGraphic(g, library) })),
    ),
  );
  root.file(
    'README.md',
    `# ${show.name} — show package\n\nGenerated by NoaCG Studio.\n\n` +
      `Each folder is one plug-and-play SPX template (rundown order):\n\n` +
      show.graphics.map((g) => `- ${slug(g.name)}/  (${g.type})`).join('\n') +
      `\n\n## Operating the show (show_controlpanel.html)\n` +
      `Run each graphic's index.html as a browser source (OBS, vMix, a browser tab), then open\n` +
      `show_controlpanel.html in another tab of the SAME browser. One card per graphic: fields,\n` +
      `the state machine's buttons, and Play/Stop/Update/Next — each card drives its own\n` +
      `graphic independently over a BroadcastChannel, no server needed.\n` +
      (show.hostedSlug
        ? `\n## Hosted control (enabled)\nEach graphic also carries the HOSTED CONTROL receiver: the show's online control page\n(?control=<slug>) drives these graphics from any device, with recovery — the commands live\nin a durable log. The slug baked into js/template.js is a capability; keep it private, and\ndelete the marked "HOSTED CONTROL" block for a pure-offline graphic.\n` : '') +
      `\nExtract this folder into your SPX/CasparCG templates directory as-is.\n`,
  );
  return zip;
}
