// Game-timer scaffolding. A game-show countdown clock: f0 is the label ("ROUND 1"),
// f1 is the duration in whole minutes ("0.5" = 30 s) held in a hidden source div —
// the shared countdown runtime (shared/clock.ts) reads it and paints M:SS into the
// clock element. The animation preset only calls startClock() / stopClock().
//
// Structure contract:
//   <div class="gt">                    root — positioned by zone; opacity:0 until play()
//     <div class="gt-box">              the panel; presets pop or reveal this
//       <div class="gt-accent">?        optional accent line — line-reveal draws it first
//       <div class="gt-mask"><span id="f0">…</span></div>   the label line
//       <div class="gt-clock">…</div>   JS paints the remaining time as M:SS
//     </div>
//     hidden #f1 source SPX writes the minutes into
//   </div>
// When the clock hits zero the root gets .gt-done — the design's CSS MUST style that
// state (e.g. flip the clock to var(--accent) with a brief flash keyframe).

import type { SpxField, SpxTemplate } from '../../model/types';
import { definitionScriptBlock } from '../../model/spxDefinition';
import { resolveEasing } from '../../model/easings';
import {
  resolveOptions,
  type ResolvedOptions,
  type TemplateVariant,
  type WizardOptions,
} from '../../model/wizard';
import {
  baseSettings,
  computeScale,
  documentHtml,
  resetCanvasCss,
  resolveHeadingFont,
  rootVarsCss,
  setFieldValueJs,
  zoneCssText,
} from '../shared/base';
import { clockRuntimeJs } from '../shared/clock';
import type { PresetConfig } from '../lowerThirds/animPresets';
import { gameTimerPresetById } from './gtPresets';

export interface GameTimerDesign {
  /** Inner HTML of .gt — must contain .gt-box > .gt-mask > #f0 and a .gt-clock element. */
  html: string;
  /** Variant CSS (panel, label, clock — and the .gt-done "time's up" state). */
  css: string;
  /** Whether the design has a .gt-accent element (line-reveal presets draw it first). */
  hasAccent?: boolean;
}

export interface GameTimerMeta {
  name: string;
  description: string;
  uicolor: string;
}

function gameTimerRuntimeJs(name: string, animationBlock: string): string {
  return `// ${name} — generated by SPX GFX Builder. SPX calls update(), play(), stop(), next().

${setFieldValueJs}

// update(data): SPX sends field values as JSON; the label (f0) is written straight into
// its element, the minutes (f1) into the hidden source the countdown runtime reads.
function update(data) {
  var fields = (typeof data === 'string') ? JSON.parse(data) : data;
  for (var key in fields) {
    var el = document.getElementById(key);
    if (el) setFieldValue(el, fields[key]);
  }
  // Off air the clock previews the full duration, so a new value shows right away.
  if (!clockTimer) {
    clockSecondsLeft = clockDurationSeconds();
    renderClock();
  }
}

// play(): take the graphic on air — the entrance timeline also starts the countdown.
function play() {
  gsap.killTweensOf('*');
  buildInTimeline();
}

// stop(): take the graphic off air — the exit timeline also stops the countdown.
function stop() {
  gsap.killTweensOf('*');
  buildOutTimeline();
}

// next(): game timers have no steps.
function next() {}

${animationBlock}
`;
}

const LABEL_SAMPLE = 'ROUND 1';
const MINUTES_SAMPLE = '3';

/** Build the complete game-timer SpxTemplate. */
export function assembleGameTimer(meta: GameTimerMeta, design: GameTimerDesign, o: ResolvedOptions): SpxTemplate {
  const font = resolveHeadingFont(o);
  const scale = computeScale(o);
  // The auto-fit cap: timers may run wide (label + big clock), so ~70 % of the canvas.
  const maxTextWidth = Math.round(o.resolution.width * 0.7);

  const labelText = o.lines[0]?.sample || LABEL_SAMPLE;
  const fields: SpxField[] = [
    { field: 'f0', ftype: 'textfield', title: o.lines[0]?.title || 'Label', value: labelText },
    { field: 'f1', ftype: 'textfield', title: 'Timer (minutes)', value: MINUTES_SAMPLE },
  ];

  const settings = baseSettings(meta, o, { steps: '1' });

  const html = documentHtml({
    title: meta.name,
    definitionBlock: definitionScriptBlock(settings, fields),
    body: `  <!-- ${meta.name}. The clock text is painted by the countdown runtime (M:SS). -->
  <div class="gt">
${design.html}
    <!-- Hidden duration source — SPX writes field f1 (minutes) here; JS reads it. -->
    <div id="f1" style="display: none">${MINUTES_SAMPLE}</div>
  </div>`,
  });

  const css = `/* ${meta.name} — generated by SPX GFX Builder. Edit freely: this file is yours. */

${rootVarsCss(o, font.stack, scale)}

${font.face}

${resetCanvasCss(o.resolution)}

/* ── Root position (anchor zone) ── */
.gt {
  position: absolute;
${zoneCssText(o.zone, o.nudge, o.resolution)}
  opacity: 0;                      /* hidden until play() runs the entrance */
}

/* ── Auto-fit: the panel hugs its text and wraps instead of overflowing. ── */
.gt-box {
  width: fit-content;              /* the panel hugs the text */
  max-width: ${maxTextWidth}px;             /* never wider than this — text wraps instead */
  will-change: transform, opacity; /* hint the browser: this element animates */
}
.gt-mask {
  overflow: hidden;                /* lines animate in from behind this mask */
}
.gt-mask > span {
  display: inline-block;           /* so the line can move inside its mask */
  overflow-wrap: break-word;       /* break very long unbroken words */
  text-wrap: balance;              /* wrapped rows get even lengths */
}

/* ── Design ── */
${design.css}
`;

  const preset = gameTimerPresetById(o.animation.presetId);
  const ease = resolveEasing(o.animation.easing, preset.autoEase);
  const cfg: PresetConfig = {
    prefix: 'gt',
    lineCount: 1,
    hasAccent: design.hasAccent === true,
    steps: false,
    speed: o.animation.speed,
    easeIn: ease.easeIn,
    easeOut: ease.easeOut,
  };

  const js = gameTimerRuntimeJs(
    meta.name,
    `${clockRuntimeJs('gt', 'f1')}

${preset.emit(cfg)}`,
  );

  return {
    name: meta.name,
    type: 'countdown',
    resolution: o.resolution,
    fps: o.fps,
    html,
    css,
    js,
    fields,
    settings,
    assets: [...o.importedImages, ...(o.customFont ? [o.customFont.asset] : [])],
    layers: [],
  };
}

/** The authoring API for game-timer variant modules. */
export function defineGameTimerVariant(
  spec: Omit<TemplateVariant, 'create'>,
  meta: GameTimerMeta,
  buildDesign: (o: ResolvedOptions) => GameTimerDesign,
): TemplateVariant {
  const variant: TemplateVariant = {
    ...spec,
    create(options?: WizardOptions) {
      const o = resolveOptions(variant, options);
      return assembleGameTimer(meta, buildDesign(o), o);
    },
  };
  return variant;
}
