// Game-timer scaffolding. A game-show countdown clock: f0 is the label ("ROUND 1"),
// f1 is the duration in whole minutes ("0.5" = 30 s) held in a hidden source div —
// the shared countdown runtime (shared/clock.ts) reads it and paints M:SS into the
// clock element. The animation preset only calls startClock() / stopClock().
//
// Structure contract:
//   <div class="game-timer">                    root — positioned by zone; opacity:0 until play()
//     <div class="game-timer-box">              the panel; presets pop or reveal this
//       <div class="game-timer-accent">?        optional accent line — line-reveal draws it first
//       <div class="game-timer-mask"><span id="f0">…</span></div>   the label line
//       <div class="game-timer-clock">…</div>   JS paints the remaining time as M:SS
//     </div>
//     hidden #f1 source SPX writes the minutes into
//   </div>
// When the clock hits zero the root gets .game-timer-done — the design's CSS MUST style that
// state (e.g. flip the clock to var(--accent) with a brief flash keyframe).

import type { SpxField, SpxTemplate } from '../../model/types';
import { definitionScriptBlock } from '../../model/spxDefinition';
import { resolveEasing } from '../../model/easings';
import {
  resolveOptions,
  type ResolvedOptions,
  type TemplateVariant,
  type WizardOptions,
} from '../../model/wizard';
import {
  baseSettings,
  computeScale,
  documentHtml,
  maxTextWidthCss,
  resetCanvasCss,
  resolveHeadingFont,
  rootVarsCss,
  setFieldValueJs,
  zoneCssText,
} from '../shared/base';
import { clockRuntimeJs } from '../shared/clock';
import { convertToDataRegion } from '../shared/standard';
import type { PresetConfig } from '../lowerThirds/animPresets';
import { gameTimerPresetById } from './gtPresets';

export interface GameTimerDesign {
  /** Inner HTML of .game-timer — must contain .game-timer-box > .game-timer-mask > #f0 and a .game-timer-clock element. */
  html: string;
  /** Variant CSS (panel, label, clock — and the .game-timer-done "time's up" state). */
  css: string;
  /** Whether the design has a .game-timer-accent element (line-reveal presets draw it first). */
  hasAccent?: boolean;
  /**
   * The design's hand-tuned default ease pair, used when the wizard easing is 'auto'
   * (it replaces the preset's autoEase; an explicit easing pick still wins). This is how
   * a deliberately playful design gets its elastic entrance without a whole new preset.
   */
  autoEase?: { easeIn: string; easeOut: string };
  /**
   * Design-owned runtime JS emitted after the clock runtime and BEFORE the marked
   * ANIMATION region (the corner bug's runtimeExtraJs pattern): playout logic like a
   * drain-ring painter lives here, survives the data conversion untouched, and must
   * never reach into the region's variables (read speed via motionSpeed() if needed).
   */
  runtimeExtraJs?: string;
}

export interface GameTimerMeta {
  name: string;
  description: string;
  uicolor: string;
}

function gameTimerRuntimeJs(name: string, animationBlock: string): string {
  return `// ${name} — generated by NoaCG Studio. SPX calls update(), play(), stop(), next().

${setFieldValueJs}

// update(data): SPX sends field values as JSON; the label (f0) is written straight into
// its element, the minutes (f1) into the hidden source the countdown runtime reads.
function update(data) {
  var fields = (typeof data === 'string') ? JSON.parse(data) : data;
  for (var key in fields) {
    var el = document.getElementById(key);
    if (el) setFieldValue(el, fields[key]);
  }
  // Off air the clock previews the full duration, so a new value shows right away.
  if (!clockTimer) {
    clockSecondsLeft = clockDurationSeconds();
    renderClock();
  }
}

// play(): take the graphic on air — the entrance timeline also starts the countdown.
function play() {
  gsap.killTweensOf('*');
  buildInTimeline();
}

// stop(): take the graphic off air — the exit timeline also stops the countdown.
function stop() {
  gsap.killTweensOf('*');
  buildOutTimeline();
}

// next(): SPX Continue — advance one step along the default path. This design ships
// single-step, so it normally does nothing; it still funnels to the interpreter so a
// template that GROWS a step (or a state machine) stays drivable through the SPX contract.
function next() {
  return (typeof revealNextStep === 'function') ? revealNextStep() : null;
}

${animationBlock}
`;
}

const LABEL_SAMPLE = 'ROUND 1';
const MINUTES_SAMPLE = '3';

/** Build the complete game-timer SpxTemplate. */
export function assembleGameTimer(meta: GameTimerMeta, design: GameTimerDesign, o: ResolvedOptions): SpxTemplate {
  const font = resolveHeadingFont(o);
  const scale = computeScale(o);
  // The auto-fit cap: timers may run wide (label + big clock), so ~70 % of the canvas.
  const maxTextWidth = Math.round(o.resolution.width * 0.7);

  const labelText = o.lines[0]?.sample || LABEL_SAMPLE;
  const fields: SpxField[] = [
    { field: 'f0', ftype: 'textfield', title: o.lines[0]?.title || 'Label', value: labelText },
    { field: 'f1', ftype: 'textfield', title: 'Timer (minutes)', value: MINUTES_SAMPLE },
  ];

  const settings = baseSettings(meta, o, { steps: '1' });

  const html = documentHtml({
    title: meta.name,
    definitionBlock: definitionScriptBlock(settings, fields),
    body: `  <!-- ${meta.name}. The clock text is painted by the countdown runtime (M:SS). -->
  <div class="game-timer">
${design.html}
    <!-- Hidden duration source — SPX writes field f1 (minutes) here; JS reads it. -->
    <div id="f1" style="display: none">${MINUTES_SAMPLE}</div>
  </div>`,
  });

  const css = `/* ${meta.name} — generated by NoaCG Studio. Edit freely: this file is yours. */

${rootVarsCss(o, font.stack, scale)}

${font.face}

${resetCanvasCss(o.resolution)}

/* ── Root position (anchor zone) ── */
.game-timer {
  position: absolute;
${zoneCssText(o.zone, o.nudge, o.resolution)}
  opacity: 0;                      /* hidden until play() runs the entrance */
}

/* ── Auto-fit: the panel hugs its text and wraps instead of overflowing. ── */
.game-timer-box {
  width: fit-content;              /* the panel hugs the text */
  max-width: ${maxTextWidthCss(o.resolution, maxTextWidth)};  /* the wrap cap — follows --scale, stops at the safe area */
  will-change: transform, opacity; /* hint the browser: this element animates */
}
.game-timer-mask {
  overflow: hidden;                /* lines animate in from behind this mask */
}
.game-timer-mask > span {
  display: inline-block;           /* so the line can move inside its mask */
  overflow-wrap: break-word;       /* break very long unbroken words */
  text-wrap: balance;              /* wrapped rows get even lengths */
}

/* ── Design ── */
${design.css}
`;

  const preset = gameTimerPresetById(o.animation.presetId);
  // 'auto' easing resolves to the design's hand-tuned pair when it declares one (a
  // playful badge wants its elastic pop by default); the preset's pair otherwise.
  const ease = resolveEasing(o.animation.easing, design.autoEase ?? preset.autoEase);
  const cfg: PresetConfig = {
    prefix: 'game-timer',
    lineCount: 1,
    hasAccent: design.hasAccent === true,
    steps: false,
    speed: o.animation.speed,
    easeIn: ease.easeIn,
    easeOut: ease.easeOut,
  };

  // Clock runtime, then any design-owned runtime, then the marked ANIMATION region —
  // everything before the region is playout logic the Animation panel never touches.
  const runtimeBlocks = [clockRuntimeJs('game-timer', 'f1')];
  if (design.runtimeExtraJs) runtimeBlocks.push(design.runtimeExtraJs);
  runtimeBlocks.push(preset.emit(cfg));
  const js = gameTimerRuntimeJs(meta.name, runtimeBlocks.join('\n\n'));

  const template: SpxTemplate = {
    name: meta.name,
    type: 'countdown',
    resolution: o.resolution,
    fps: o.fps,
    html,
    css,
    js,
    fields,
    settings,
    assets: [...o.importedImages, ...(o.customFont ? [o.customFont.asset] : [])],
    layers: [],
  };

  // Timeline v2: convert the marked region into the NOACG_ANIM data block + interpreter.
  // The step-calls model (docs/TIMELINE_V2_PLAN.md §3b) carries the preset's
  // startClock()/stopClock() hooks, so the countdown survives the flip; the clock runtime
  // itself lives OUTSIDE the region and is untouched. A conversion failure keeps the legacy
  // emit — never a broken template.
  return convertToDataRegion(template);
}

/**
 * Design-owned runtime for the badge-style timers (gt03/gt04): a drain ring that follows
 * the shared countdown, a "last three seconds" urgency state, and a small accent on the
 * clock each tick. This is playout logic like the clock engine itself, so it is emitted
 * OUTSIDE the marked ANIMATION region (via GameTimerDesign.runtimeExtraJs) and survives
 * the data conversion and every preset swap untouched.
 *
 * Contract with the design:
 *   - an SVG circle with class "game-timer-ring-fill", r = 180 in its viewBox (that is the
 *     1131 circumference below), with a CSS transition on stroke-dashoffset so each
 *     one-second step glides instead of jumping
 *   - the root gets .game-timer-ending while three or fewer seconds tick — the design's
 *     CSS decides what urgency looks like (a pulse, a glow)
 *
 * `tick` picks the clock's per-second accent: 'bounce' is the exuberant elastic pop,
 * 'snap' the crisp controlled one. Both settle at scale 1, so a replay starts clean.
 */
export function badgeRingRuntimeJs(tick: 'bounce' | 'snap'): string {
  const pop =
    tick === 'bounce'
      ? `    // The playful beat: the clock bounces on every tick, elastic like a toy.
    gsap.fromTo('.game-timer-clock',
      { scale: 1.22, transformOrigin: '50% 50%' },
      { scale: 1, duration: 0.55, ease: 'elastic.out(1, 0.4)' });`
      : `    // The crisp beat: a small controlled snap on every tick — lively, never wobbly.
    gsap.fromTo('.game-timer-clock',
      { scale: 0.94, transformOrigin: '50% 50%' },
      { scale: 1, duration: 0.18, ease: 'power2.out' });`;
  return `// ── Badge drain ring ────────────────────────────────────────────────────
// The ring around the badge empties as the countdown runs. The clock runtime above owns
// the time (clockTimer / clockSecondsLeft / clockDurationSeconds); this painter just looks
// a few times a second, and the ring's CSS transition glides each one-second step.
var RING_CIRCUMFERENCE = 1131;  // 2 × π × r for the ring circle (r = 180 in its viewBox)
var ringPaintedSecond = null;   // the remaining-seconds value we last painted

function paintRing() {
  var ring = document.querySelector('.game-timer-ring-fill');
  var root = document.querySelector('.game-timer');
  if (!ring || !root) return;   // template.js loads in <head> — wait until the DOM exists
  var total = clockDurationSeconds();
  // Off air the ring previews full; at zero it stays empty until the next play().
  var left = clockTimer ? clockSecondsLeft
    : (root.classList.contains('game-timer-done') ? 0 : total);
  if (left === ringPaintedSecond) return;   // nothing changed since the last look
  var ticked = !!clockTimer && ringPaintedSecond !== null && left < ringPaintedSecond;
  ringPaintedSecond = left;
  // Hide exactly the elapsed fraction of the ring (the dashoffset covers the rest).
  ring.style.strokeDashoffset = (RING_CIRCUMFERENCE * (1 - left / total)) + 'px';
  // The last three ticking seconds get an urgency class the design's CSS can pulse.
  root.classList.toggle('game-timer-ending', !!clockTimer && left > 0 && left <= 3);
  if (ticked) {
${pop}
  }
}
setInterval(paintRing, 150);    // a few cheap looks a second — never more than one repaint`;
}

/** The authoring API for game-timer variant modules. */
export function defineGameTimerVariant(
  spec: Omit<TemplateVariant, 'create'>,
  meta: GameTimerMeta,
  buildDesign: (o: ResolvedOptions) => GameTimerDesign,
): TemplateVariant {
  const variant: TemplateVariant = {
    ...spec,
    create(options?: WizardOptions) {
      const o = resolveOptions(variant, options);
      return assembleGameTimer(meta, buildDesign(o), o);
    },
  };
  return variant;
}
