// Transition scaffolding — the full-frame moment that hides a cut: a stinger, a wipe, a replay
// bumper. docs/PACK_TAXONOMY.md's gap list had these down as "the versus card's territory,
// worth a dedicated stinger type if demand shows"; what makes them a category of their own is
// not the drawing but the LIFECYCLE.
//
// Every other graphic in the catalog is on air until an operator takes it off. A transition is
// on air for about a second, on purpose, and its middle is the point: it covers the frame,
// holds while the vision mixer cuts underneath, and clears to reveal whatever is now there.
// That "hold, then clear yourself" is a real state machine with a timer on it, and it is
// declared by the transition TYPE (src/templates/types/transitions.ts) — a timer arrow from
// the entrance waypoint straight to the exit, with `next` as the manual version. No preset here
// schedules anything: a setTimeout inside a template is motion the timeline cannot see, the
// control page cannot pause and the render clock cannot drive.
//
// Structure contract (the transition presets rely on it):
//   <div class="transition">                 root — covers the canvas; opacity:0 until play()
//     <div class="transition-box">           the full-frame stage; presets animate this
//       <div class="transition-panel">…</div>  one or more COVERING surfaces
//       <div class="transition-mark">          the centred lockup
//         <div class="transition-mask"><span id="f0" class="transition-label">…</span></div>
//       </div>
//     </div>
//   </div>
//
// The panels are authored AT their covering position in CSS, so the still a thumbnail or a
// baseline captures is the cover moment — which is what the graphic is for.

import type { SpxField, SpxTemplate } from '../../model/types';
import { definitionScriptBlock } from '../../model/spxDefinition';
import { resolveEasing } from '../../model/easings';
import {
  resolveOptions,
  type ResolvedOptions,
  type TemplateVariant,
  type WizardOptions,
} from '../../model/wizard';
import {
  baseSettings,
  computeScale,
  documentHtml,
  resetCanvasCss,
  resolveHeadingFont,
  rootVarsCss,
  runtimeJs,
  zoneCssText,
} from '../shared/base';
import type { AnimData } from '../../blocks/animData';
import { convertToDataRegion } from '../shared/standard';
import type { PresetConfig } from '../lowerThirds/animPresets';
import { transitionPresetById } from './transitionPresets';
import { resolveTokens, type ThemeTokens, type TokenOverrides } from '../../model/themeTokens';

export interface TransitionDesign {
  /** Inner HTML of .transition — must contain .transition-box holding at least one
   *  .transition-panel and a .transition-mark whose label is `.transition-mask > span#f0`. */
  html: string;
  /** Variant CSS (the covering surfaces and the mark). Colors via the :root vars only. */
  css: string;
  /**
   * Where this design disagrees with its style family's shape tokens
   * (model/themeTokens.ts). Every entry is conformance debt - DESIGN_LANGUAGE §8's rule is
   * "reuse the exact token values, don't improvise new ones per category".
   */
  tokens?: TokenOverrides;
}

export interface TransitionMeta {
  name: string;
  description: string;
  /** SPX UI color label, "1".."7". */
  uicolor: string;
}

/** The label field — every transition carries exactly one, and it may be left blank. */
function transitionFields(o: ResolvedOptions): SpxField[] {
  return [
    {
      field: 'f0',
      ftype: 'textfield',
      title: o.lines[0]?.title || 'Label',
      value: o.lines[0]?.sample ?? '',
    },
  ];
}

/** Build the complete transition SpxTemplate. */
export function assembleTransition(
  meta: TransitionMeta,
  design: TransitionDesign,
  o: ResolvedOptions,
  /** Refine the converted animation data — the seam the transition TYPE injects its
   *  timer machine through (see shared/standard.ts composeRefine for the ordering rule). */
  refine?: (data: AnimData) => AnimData,
  /** The design's resolved SHAPE tokens (model/themeTokens.ts), resolved by the caller
   *  because the family lives on the VARIANT and this function only sees the design. */
  tokens?: ThemeTokens,
): SpxTemplate {
  const font = resolveHeadingFont(o); // imported font wins over the bundled set
  const scale = computeScale(o);
  const fields = transitionFields(o);
  // A transition has one beat and no reveal sequence: cover, hold, clear.
  const settings = baseSettings(meta, o, { steps: '1' });

  const html = documentHtml({
    title: meta.name,
    definitionBlock: definitionScriptBlock(settings, fields),
    body: `  <!-- Transition — covers the frame so a cut can happen underneath, then clears. -->
  <div class="transition">
${design.html}
  </div>`,
  });

  const css = `/* ${meta.name} — generated by NoaCG Studio. Edit freely: this file is yours. */

${rootVarsCss(o, font.stack, scale, { tokens, consumerCss: design.css })}

${font.face}

${resetCanvasCss(o.resolution)}

/* ── Root position — a transition covers the whole canvas. ── */
.transition {
  position: absolute;
${zoneCssText(o.zone, o.nudge, o.resolution)}
  width: ${o.resolution.width}px;   /* the cover reaches every edge… */
  height: ${o.resolution.height}px;  /* …both ways */
  opacity: 0;                      /* hidden until play() runs the entrance */
}

/* ── The stage. Nothing here ever intercepts a click: in a browser-source overlay a
      transition passes over the frame for a second and must leave no trace behind it. ── */
.transition-box {
  position: relative;              /* the panels and the mark are placed against this stage */
  width: 100%;                     /* fills the canvas… */
  height: 100%;                    /* …both ways */
  overflow: hidden;                /* the panels travel from off-frame — nothing paints outside */
  pointer-events: none;            /* a transition never intercepts anything */
  will-change: transform, opacity; /* hint the browser: this element animates */
}

/* ── A covering surface. Authored AT its covering position, so the graphic's rest pose is
      the cut point; the presets are what take it off frame and bring it back. ── */
.transition-panel {
  position: absolute;              /* each panel states its own band */
  will-change: transform, filter;  /* the panels travel, and one preset blurs them */
}

/* ── The centred lockup. ── */
.transition-mark {
  position: absolute;              /* a full-frame wrapper: scaling it pivots on the centre */
  inset: 0;                        /* edge to edge */
  display: flex;                   /* centres the label… */
  align-items: center;             /* …vertically… */
  justify-content: center;         /* …and horizontally */
  will-change: transform, opacity; /* the mark snaps on over the cover */
}

/* ── Auto-fit for the label: it wraps in the middle of the frame instead of running off it. ── */
.transition-mask {
  overflow: hidden;                /* the label can reveal from behind this mask */
  max-width: ${Math.round(o.resolution.width * 0.7)}px;  /* never reaches the frame edges */
}
.transition-mask > span {
  display: inline-block;           /* so the label can move inside its mask */
  overflow-wrap: break-word;       /* break a very long unbroken label */
  text-wrap: balance;              /* wrapped rows get even lengths */
  text-align: center;              /* the lockup is centre-axis */
}

/* ── Design ── */
${design.css}
`;

  const preset = transitionPresetById(o.animation.presetId);
  // 'auto' uses the preset's hand-tuned ease pair; a named easing preset overrides both phases.
  const ease = resolveEasing(o.animation.easing, preset.autoEase);
  const cfg: PresetConfig = {
    prefix: 'transition',
    lineCount: 1, // the label, and only the label
    hasAccent: false,
    steps: false, // cover, hold, clear — there is nothing to reveal on Continue
    speed: o.animation.speed,
    easeIn: ease.easeIn,
    easeOut: ease.easeOut,
  };

  const js = runtimeJs(meta.name, preset.emit(cfg));

  return convertToDataRegion(
    {
      name: meta.name,
      type: 'transition',
      resolution: o.resolution,
      fps: o.fps,
      html,
      css,
      js,
      fields,
      settings,
      assets: [...o.importedImages, ...(o.customFont ? [o.customFont.asset] : [])],
      layers: fields.map((f) => ({
        id: f.field,
        type: 'text' as const,
        label: f.title,
        fieldId: f.field,
        text: f.value,
        styles: {},
      })),
    },
    refine,
  );
}

/** The authoring API for transition variant modules. */
export function defineTransitionVariant(
  spec: Omit<TemplateVariant, 'create'>,
  meta: TransitionMeta,
  buildDesign: (o: ResolvedOptions) => TransitionDesign,
  /** Optional animation-data refinement (the type's timer machine rides in here). */
  refine?: (o: ResolvedOptions) => ((data: AnimData) => AnimData) | undefined,
): TemplateVariant {
  const variant: TemplateVariant = {
    ...spec,
    create(options?: WizardOptions) {
      const o = resolveOptions(variant, options);
      const design = buildDesign(o);
      const tokens = resolveTokens(spec.styleTag, design.tokens);
      return assembleTransition(meta, design, o, refine?.(o), tokens);
    },
  };
  return variant;
}
