// The category-generic assembler: every "standard contract" category (lower thirds, info
// cards, …) is the same machine with a different class prefix + structure comment + width cap.
// A category module defines its CategorySpec once; variants stay tiny design builders.

import type { SpxField, SpxTemplate, TemplateType, Resolution } from '../../model/types';
import { definitionScriptBlock } from '../../model/spxDefinition';
import { resolveEasing } from '../../model/easings';
import {
  fieldsFromOptions,
  resolveOptions,
  type ResolvedOptions,
  type TemplateVariant,
  type WizardOptions,
} from '../../model/wizard';
import {
  baseSettings,
  computeMaxTextWidth,
  computeScale,
  documentHtml,
  resetCanvasCss,
  resolveHeadingFont,
  rootVarsCss,
  runtimeJs,
  zoneCssText,
} from './base';
import { presetById, type PresetConfig } from '../lowerThirds/animPresets';

export interface StandardDesign {
  /** Inner HTML of the .<prefix> root (accent + box with masked lines). */
  html: string;
  /** Variant-specific CSS. All colors via the :root vars, sizes via calc(*var(--scale)). */
  css: string;
  /** Whether the design includes a .<prefix>-accent element. */
  hasAccent: boolean;
  /**
   * Fields the DESIGN owns beyond the wizard lines — e.g. an image field ("filelist")
   * bound to an <img id="fN"> logo slot. Appended after the line/extra fields.
   */
  extraFields?: SpxField[];
  /**
   * Set when steps mode (SPX Continue) is semantically meaningless for the design —
   * e.g. a versus card whose lines are simultaneous columns, not a reveal sequence.
   * The wizard's steps flag is then ignored for this variant.
   */
  disableSteps?: boolean;
  /**
   * Extra runtime JS the design owns (e.g. a live clock painter). Emitted BEFORE the
   * marked ANIMATION region — same doctrine as infographics — so the Motion panel can
   * never rewrite it. Any load-time DOM work in it must use the DOM-ready guard
   * (template.js loads in <head> in exported packages).
   */
  runtimeExtraJs?: string;
}

export interface StandardMeta {
  name: string;
  description: string;
  /** SPX UI color label, "1".."7". */
  uicolor: string;
}

export interface CategorySpec {
  type: TemplateType;
  /** Class prefix for the structure contract ('l3', 'card', …). */
  prefix: string;
  /** One-line body comment describing the root element. */
  rootComment: string;
  /** The auto-fit width cap for this category (cards may be wider than straps). */
  maxTextWidth?: (res: Resolution) => number;
}

/** Class name for the Nth line of a category (0 = heading/name, 1 = title/body, 2+ = extra). */
export function lineClassFor(prefix: string, index: number): string {
  return [`${prefix}-name`, `${prefix}-title`, `${prefix}-extra`][index] ?? `${prefix}-extra`;
}

/** The mask-wrapped line elements (SPX writes straight into id="fN"). */
export function lineMasksFor(prefix: string, o: ResolvedOptions, indent = '      '): string {
  return o.lines
    .map(
      (line, i) =>
        `${indent}<!-- ${line.title} (f${i}) — SPX writes this field's value straight into the element. -->\n` +
        `${indent}<div class="${prefix}-mask"><span id="f${i}" class="${lineClassFor(prefix, i)}">${line.sample}</span></div>`,
    )
    .join('\n');
}

/** Build the complete SpxTemplate for a standard-contract category. */
export function assembleStandard(
  cat: CategorySpec,
  meta: StandardMeta,
  design: StandardDesign,
  o: ResolvedOptions,
): SpxTemplate {
  const p = cat.prefix;
  const font = resolveHeadingFont(o); // imported font wins over the bundled set
  const fields = [...fieldsFromOptions(o), ...(design.extraFields ?? [])];
  // A design may opt out of steps mode (see StandardDesign.disableSteps); SPX then
  // treats the graphic as single-step regardless of the wizard's steps flag.
  const settings = baseSettings(meta, o, design.disableSteps ? { steps: '1' } : undefined);
  const scale = computeScale(o);
  const maxTextWidth = (cat.maxTextWidth ?? computeMaxTextWidth)(o.resolution);

  const html = documentHtml({
    title: meta.name,
    definitionBlock: definitionScriptBlock(settings, fields),
    body: `  <!-- ${cat.rootComment} -->
  <div class="${p}">
${design.html}
  </div>`,
  });

  const css = `/* ${meta.name} — generated by NoaCG Studio. Edit freely: this file is yours. */

${rootVarsCss(o, font.stack, scale)}

${font.face}

${resetCanvasCss(o.resolution)}

/* ── Root position (anchor zone) ── */
.${p} {
  position: absolute;
${zoneCssText(o.zone, o.nudge, o.resolution)}
  opacity: 0;                      /* hidden until play() runs the entrance */
}

/* ── Auto-fit: the panel hugs its text and wraps instead of overflowing. ── */
.${p}-box {
  width: fit-content;              /* the panel hugs the text */
  max-width: ${maxTextWidth}px;              /* never wider than this — text wraps instead */
  will-change: transform, opacity; /* hint the browser: this element animates */
}
.${p}-mask {
  overflow: hidden;                /* lines animate in from behind this mask */
}
.${p}-mask > span {
  display: inline-block;           /* so the line can move inside its mask */
  overflow-wrap: break-word;       /* break very long unbroken words */
  text-wrap: balance;              /* wrapped rows get even lengths */
}

/* ── Design ── */
${design.css}
`;

  const preset = presetById(o.animation.presetId);
  // 'auto' uses the preset's hand-tuned ease pair; a named easing preset overrides both phases.
  const ease = resolveEasing(o.animation.easing, preset.autoEase);
  const presetCfg: PresetConfig = {
    prefix: p,
    lineCount: o.lines.length,
    hasAccent: design.hasAccent,
    steps: o.animation.steps && o.lines.length > 1 && !design.disableSteps,
    speed: o.animation.speed,
    easeIn: ease.easeIn,
    easeOut: ease.easeOut,
  };

  // Design-owned runtime (e.g. a live clock) lives OUTSIDE the marked ANIMATION region —
  // before it — so preset/steps swaps in the Motion panel can never rewrite it.
  const extraJs = design.runtimeExtraJs?.trim();
  const js = runtimeJs(meta.name, extraJs ? `${extraJs}\n\n${preset.emit(presetCfg)}` : preset.emit(presetCfg));

  return {
    name: meta.name,
    type: cat.type,
    resolution: o.resolution,
    fps: o.fps,
    html,
    css,
    js,
    fields,
    settings,
    assets: [...o.importedImages, ...(o.customFont ? [o.customFont.asset] : [])],
    layers: o.lines.map((line, i) => ({
      id: `f${i}`,
      type: 'text' as const,
      label: line.title,
      fieldId: `f${i}`,
      text: line.sample,
      styles: {},
    })),
  };
}

/** The authoring factory: a category gets its own defineVariant with everything wired. */
export function makeDefineVariant(cat: CategorySpec) {
  return function defineVariant(
    spec: Omit<TemplateVariant, 'create'>,
    meta: StandardMeta,
    buildDesign: (o: ResolvedOptions) => StandardDesign,
  ): TemplateVariant {
    const variant: TemplateVariant = {
      ...spec,
      create(options?: WizardOptions) {
        const o = resolveOptions(variant, options);
        return assembleStandard(cat, meta, buildDesign(o), o);
      },
    };
    return variant;
  };
}
