// Ticker scaffolding. Tickers are data-driven: a textarea field (f0) holds the items —
// one per line — and f1 is the strip's label ("BREAKING", the show name…). The template's
// JS renders the items at runtime; the marquee preset needs them rendered TWICE for a
// seamless loop, so rebuildTicker() handles that automatically.
//
// Structure contract:
//   <div class="ticker">                root — positioned by zone; opacity:0 until play()
//     <div class="ticker-box">          the strip; presets fade this
//       [<div class="ticker-label"><span id="f1">…</span></div>]   optional label block
//       <div class="ticker-viewport">   overflow hidden window
//         <div id="ticker-track">       items injected by rebuildTicker()
//       </div>
//     </div>
//     hidden #f0 source SPX writes into
//   </div>

import type { SpxField, SpxTemplate } from '../../model/types';
import { definitionScriptBlock } from '../../model/spxDefinition';
import { resolveEasing } from '../../model/easings';
import {
  resolveOptions,
  type ResolvedOptions,
  type TemplateVariant,
  type WizardOptions,
} from '../../model/wizard';
import {
  baseSettings,
  computeScale,
  documentHtml,
  resetCanvasCss,
  resolveHeadingFont,
  rootVarsCss,
  setFieldValueJs,
  zoneCssText,
} from '../shared/base';
import type { PresetConfig } from '../lowerThirds/animPresets';
import type { AnimData } from '../../blocks/animData';
import { convertToDataRegion } from '../shared/standard';
import { tickerPresetById } from './tickerPresets';
import { TICKER_MOTION_JS } from './tickerMotion';
import { resolveTokens, type ThemeTokens, type TokenOverrides } from '../../model/themeTokens';

export interface TickerDesign {
  /** Inner HTML of .ticker — must contain .ticker-box > .ticker-viewport > #ticker-track. */
  html: string;
  /** Variant CSS (strip, label, items, separators). */
  css: string;
  /** JS defining renderTickerItem(text) — the markup for one item (include your separator). */
  rowBuilderJs: string;
  /** Whether the marquee needs the items doubled for a seamless loop (flip designs don't). */
  doubleItems: boolean;
  /**
   * Where this design disagrees with its style family's shape tokens
   * (model/themeTokens.ts). Every entry is conformance debt - DESIGN_LANGUAGE §8's rule is
   * "reuse the exact token values, don't improvise new ones per category".
   */
  tokens?: TokenOverrides;
}

export interface TickerMeta {
  name: string;
  description: string;
  uicolor: string;
}

function tickerRuntimeJs(name: string, animationBlock: string): string {
  return `// ${name} — generated by NoaCG Studio. SPX calls update(), play(), stop(), next().

// rebuildTicker(): re-render the items from the hidden #f0 source (one item per line).
function rebuildTicker() {
  var track = document.getElementById('ticker-track');
  // A ROTATING ticker shows one item at a time and the graphic's own timer advances it, so
  // rendering the whole list here would both look wrong and pile every item into the strip at
  // once. Hand it back to the rotator instead.
  if (TICKER_ROTATE && typeof tickerShowNext === 'function') { tickerShowCurrent(); return; }
  var lines = document.getElementById('f0').textContent.split('\\n');
  var html = '';
  lines.forEach(function (raw) {
    var item = raw.trim();
    if (item !== '') html += renderTickerItem(item);
  });
  // The marquee loop needs the set twice: sliding one set length reads as endless.
  track.innerHTML = TICKER_DOUBLE_ITEMS ? html + html : html;
}

${setFieldValueJs}

// update(data): SPX sends field values as JSON; the label (f1) is written straight into
// its element, the items (f0) into the hidden source — then the track re-renders.
function update(data) {
  var fields = (typeof data === 'string') ? JSON.parse(data) : data;
  for (var key in fields) {
    var el = document.getElementById(key);
    if (el) setFieldValue(el, fields[key]);
  }
  rebuildTicker();
}

// play(): rebuild (fresh measurements), then start the loop.
function play() {
  gsap.killTweensOf('*');
  rebuildTicker();
  buildInTimeline();
}

// stop(): take the ticker off air (also stops the loop).
function stop() {
  gsap.killTweensOf('*');
  buildOutTimeline();
}

// next(): SPX Continue — advance one step along the default path. This design ships
// single-step, so it normally does nothing; it still funnels to the interpreter so a
// template that GROWS a step (or a state machine) stays drivable through the SPX contract.
function next() {
  return (typeof revealNextStep === 'function') ? revealNextStep() : null;
}

// Render once on load so the preview shows content before the first update().
// This file loads in <head>, before the ticker elements exist — wait for the DOM.
if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', rebuildTicker);
} else {
  rebuildTicker();                // DOM already parsed (e.g. an inline preview build)
}

${animationBlock}
`;
}

/**
 * Rotating tickers show ONE item at a time, advanced by the graphic's own state machine.
 *
 * Every ticker design is built for the marquee: the track is one endless nowrap row that
 * TRAVELS past a clipping viewport, so a long story is fine — it scrolls by. A rotating strip
 * has nowhere to travel to, so the same markup would just push a long story off the end of the
 * strip and into whatever cap sits there. These rules turn the track back into an ordinary
 * block that fits its viewport and wraps, which is the auto-fit pattern used everywhere else.
 */
const ROTATE_CSS = `
/* ── Rotating strip: the item FITS the viewport instead of travelling past it. ── */

/* The viewport clips because a marquee's items have to vanish at the strip's edges. Nothing
   travels here, so clipping would only ever cut a wrapped story in half — let the strip grow
   to whatever the current item needs instead. */
.ticker-viewport {
  overflow: visible;
}

#ticker-track {
  display: block;                  /* not an endless row — one item, in normal flow */
  width: 100%;                     /* fill the space the caps leave */
  white-space: normal;             /* a long story wraps rather than running off the strip */
  will-change: opacity, transform; /* the machine's beat fades and lifts it */
}

.ticker-item {
  display: block;                  /* the item is the line, not a cell in a row */
  overflow-wrap: break-word;       /* break a very long unbroken word */
}

/* The separator punctuates a ROW of stories; a rotating strip shows one at a time. */
.ticker-sep {
  display: none;
}
`;

const ITEMS_SAMPLE = [
  'Welcome to tonight’s live show',
  'Guest lineup announced for next week',
  'Send your questions with #ontheair',
  'Tickets for the summer tour are on sale now',
].join('\n');

/** Build the complete ticker SpxTemplate. */
export function assembleTicker(meta: TickerMeta, design: TickerDesign, o: ResolvedOptions,
  /** Refine the converted animation data — the seam a graphic TYPE injects its machine
   *  through (see shared/standard.ts composeRefine for the ordering rule). */
  refine?: (data: AnimData) => AnimData,
  /** The design's resolved SHAPE tokens (model/themeTokens.ts). Resolved by the caller,
   *  because the family lives on the VARIANT (styleTag) and this function only sees the
   *  design. Absent = emit no token lines, which is what every template did before they
   *  existed. */
  tokens?: ThemeTokens,
): SpxTemplate {
  const font = resolveHeadingFont(o);
  const scale = computeScale(o);

  const itemsText = o.lines[0]?.sample || ITEMS_SAMPLE;
  const labelText = o.lines[1]?.sample || 'ON AIR';
  const fields: SpxField[] = [
    { field: 'f0', ftype: 'textarea', title: o.lines[0]?.title || 'Ticker items', value: itemsText },
    { field: 'f1', ftype: 'textfield', title: o.lines[1]?.title || 'Label', value: labelText },
  ];

  const settings = baseSettings(meta, o, { steps: '1', playlayer: '3', webplayout: '3' });

  const html = documentHtml({
    title: meta.name,
    definitionBlock: definitionScriptBlock(settings, fields),
    body: `  <!-- ${meta.name}. Items are rendered by rebuildTicker() from the hidden source below. -->
  <div class="ticker">
${design.html}
    <!-- Hidden items source — SPX writes field f0 here; JS renders it. -->
    <div id="f0" style="display: none">${itemsText}</div>
  </div>`,
  });

  const css = `/* ${meta.name} — generated by NoaCG Studio. Edit freely: this file is yours. */

${rootVarsCss(o, font.stack, scale, { tokens, consumerCss: design.css })}

${font.face}

${resetCanvasCss(o.resolution)}

/* ── Root position (anchor zone) ── */
.ticker {
  position: absolute;
${zoneCssText(o.zone, o.nudge, o.resolution)}
  opacity: 0;                      /* hidden until play() runs the entrance */
}

/* ── Design ── */
${design.css}
${o.animation.presetId === 'ticker-rotate' ? ROTATE_CSS : ''}`;

  const preset = tickerPresetById(o.animation.presetId);
  const ease = resolveEasing(o.animation.easing, preset.autoEase);
  const cfg: PresetConfig = {
    prefix: 'ticker',
    lineCount: 2,
    hasAccent: false,
    steps: false,
    speed: o.animation.speed,
    easeIn: ease.easeIn,
    easeOut: ease.easeOut,
  };

  const js = tickerRuntimeJs(
    meta.name,
    `// Marquee designs render the items twice for a seamless loop; flip designs don't.
var TICKER_DOUBLE_ITEMS = ${o.animation.presetId === 'ticker-rotate' ? false : design.doubleItems};

// A ROTATING ticker shows one item at a time, advanced by the graphic's state machine rather
// than by endless motion — so the whole list never goes into the strip at once.
var TICKER_ROTATE = ${o.animation.presetId === 'ticker-rotate'};

${design.rowBuilderJs}

${TICKER_MOTION_JS}

${preset.emit(cfg)}`,
  );

  const template: SpxTemplate = {
    name: meta.name,
    type: 'ticker',
    resolution: o.resolution,
    fps: o.fps,
    html,
    css,
    js,
    fields,
    settings,
    assets: [...o.importedImages, ...(o.customFont ? [o.customFont.asset] : [])],
    layers: [],
  };

  // Timeline v2: convert the emitted region into the NOACG_ANIM data block. The strip's fade
  // becomes ordinary keyframes; the measured travel rides across as a `dynamics` segment
  // naming its builder above (docs/DYNAMIC_MOTION_SCOPE.md). The builders themselves sit
  // outside the region and are untouched by the conversion.
  return convertToDataRegion(template, refine);
}

/** The authoring API for ticker variant modules. */
export function defineTickerVariant(
  spec: Omit<TemplateVariant, 'create'>,
  meta: TickerMeta,
  buildDesign: (o: ResolvedOptions) => TickerDesign,
  /** Optional animation-data refinement (a graphic type's machine rides in here). It is
   *  built per create() because a type's compiled machine depends on the resolved options. */
  refine?: (o: ResolvedOptions) => ((data: AnimData) => AnimData) | undefined,
): TemplateVariant {
  const variant: TemplateVariant = {
    ...spec,
    create(options?: WizardOptions) {
      const o = resolveOptions(variant, options);
      const design = buildDesign(o);
      // The family lives on the variant, the overrides on the design — resolved here
      // because this is the only place that holds both.
      const tokens = resolveTokens(spec.styleTag, design.tokens);
      return assembleTicker(meta, design, o, refine?.(o), tokens);
    },
  };
  return variant;
}
