// Ticker scaffolding. Tickers are data-driven: a textarea field (f0) holds the items —
// one per line — and f1 is the strip's label ("BREAKING", the show name…). The template's
// JS renders the items at runtime; the marquee preset needs them rendered TWICE for a
// seamless loop, so rebuildTicker() handles that automatically.
//
// Structure contract:
//   <div class="ticker">                root — positioned by zone; opacity:0 until play()
//     <div class="ticker-box">          the strip; presets fade this
//       [<div class="ticker-label"><span id="f1">…</span></div>]   optional label block
//       <div class="ticker-viewport">   overflow hidden window
//         <div id="ticker-track">       items injected by rebuildTicker()
//       </div>
//     </div>
//     hidden #f0 source SPX writes into
//   </div>

import type { SpxField, SpxTemplate } from '../../model/types';
import { definitionScriptBlock } from '../../model/spxDefinition';
import { resolveEasing } from '../../model/easings';
import {
  resolveOptions,
  type ResolvedOptions,
  type TemplateVariant,
  type WizardOptions,
} from '../../model/wizard';
import {
  baseSettings,
  computeScale,
  documentHtml,
  resetCanvasCss,
  resolveHeadingFont,
  rootVarsCss,
  setFieldValueJs,
  zoneCssText,
} from '../shared/base';
import type { PresetConfig } from '../lowerThirds/animPresets';
import { convertToDataRegion } from '../shared/standard';
import { tickerPresetById } from './tickerPresets';
import { TICKER_MOTION_JS } from './tickerMotion';

export interface TickerDesign {
  /** Inner HTML of .ticker — must contain .ticker-box > .ticker-viewport > #ticker-track. */
  html: string;
  /** Variant CSS (strip, label, items, separators). */
  css: string;
  /** JS defining renderTickerItem(text) — the markup for one item (include your separator). */
  rowBuilderJs: string;
  /** Whether the marquee needs the items doubled for a seamless loop (flip designs don't). */
  doubleItems: boolean;
}

export interface TickerMeta {
  name: string;
  description: string;
  uicolor: string;
}

function tickerRuntimeJs(name: string, animationBlock: string): string {
  return `// ${name} — generated by NoaCG Studio. SPX calls update(), play(), stop(), next().

// rebuildTicker(): re-render the items from the hidden #f0 source (one item per line).
function rebuildTicker() {
  var track = document.getElementById('ticker-track');
  var lines = document.getElementById('f0').textContent.split('\\n');
  var html = '';
  lines.forEach(function (raw) {
    var item = raw.trim();
    if (item !== '') html += renderTickerItem(item);
  });
  // The marquee loop needs the set twice: sliding one set length reads as endless.
  track.innerHTML = TICKER_DOUBLE_ITEMS ? html + html : html;
}

${setFieldValueJs}

// update(data): SPX sends field values as JSON; the label (f1) is written straight into
// its element, the items (f0) into the hidden source — then the track re-renders.
function update(data) {
  var fields = (typeof data === 'string') ? JSON.parse(data) : data;
  for (var key in fields) {
    var el = document.getElementById(key);
    if (el) setFieldValue(el, fields[key]);
  }
  rebuildTicker();
}

// play(): rebuild (fresh measurements), then start the loop.
function play() {
  gsap.killTweensOf('*');
  rebuildTicker();
  buildInTimeline();
}

// stop(): take the ticker off air (also stops the loop).
function stop() {
  gsap.killTweensOf('*');
  buildOutTimeline();
}

// next(): SPX Continue — advance one step along the default path. This design ships
// single-step, so it normally does nothing; it still funnels to the interpreter so a
// template that GROWS a step (or a state machine) stays drivable through the SPX contract.
function next() {
  return (typeof revealNextStep === 'function') ? revealNextStep() : null;
}

// Render once on load so the preview shows content before the first update().
// This file loads in <head>, before the ticker elements exist — wait for the DOM.
if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', rebuildTicker);
} else {
  rebuildTicker();                // DOM already parsed (e.g. an inline preview build)
}

${animationBlock}
`;
}

const ITEMS_SAMPLE = [
  'Welcome to tonight’s live show',
  'Guest lineup announced for next week',
  'Send your questions with #ontheair',
  'Tickets for the summer tour are on sale now',
].join('\n');

/** Build the complete ticker SpxTemplate. */
export function assembleTicker(meta: TickerMeta, design: TickerDesign, o: ResolvedOptions): SpxTemplate {
  const font = resolveHeadingFont(o);
  const scale = computeScale(o);

  const itemsText = o.lines[0]?.sample || ITEMS_SAMPLE;
  const labelText = o.lines[1]?.sample || 'ON AIR';
  const fields: SpxField[] = [
    { field: 'f0', ftype: 'textarea', title: o.lines[0]?.title || 'Ticker items', value: itemsText },
    { field: 'f1', ftype: 'textfield', title: o.lines[1]?.title || 'Label', value: labelText },
  ];

  const settings = baseSettings(meta, o, { steps: '1', playlayer: '3', webplayout: '3' });

  const html = documentHtml({
    title: meta.name,
    definitionBlock: definitionScriptBlock(settings, fields),
    body: `  <!-- ${meta.name}. Items are rendered by rebuildTicker() from the hidden source below. -->
  <div class="ticker">
${design.html}
    <!-- Hidden items source — SPX writes field f0 here; JS renders it. -->
    <div id="f0" style="display: none">${itemsText}</div>
  </div>`,
  });

  const css = `/* ${meta.name} — generated by NoaCG Studio. Edit freely: this file is yours. */

${rootVarsCss(o, font.stack, scale)}

${font.face}

${resetCanvasCss(o.resolution)}

/* ── Root position (anchor zone) ── */
.ticker {
  position: absolute;
${zoneCssText(o.zone, o.nudge, o.resolution)}
  opacity: 0;                      /* hidden until play() runs the entrance */
}

/* ── Design ── */
${design.css}
`;

  const preset = tickerPresetById(o.animation.presetId);
  const ease = resolveEasing(o.animation.easing, preset.autoEase);
  const cfg: PresetConfig = {
    prefix: 'ticker',
    lineCount: 2,
    hasAccent: false,
    steps: false,
    speed: o.animation.speed,
    easeIn: ease.easeIn,
    easeOut: ease.easeOut,
  };

  const js = tickerRuntimeJs(
    meta.name,
    `// Marquee designs render the items twice for a seamless loop; flip designs don't.
var TICKER_DOUBLE_ITEMS = ${design.doubleItems};

${design.rowBuilderJs}

${TICKER_MOTION_JS}

${preset.emit(cfg)}`,
  );

  const template: SpxTemplate = {
    name: meta.name,
    type: 'ticker',
    resolution: o.resolution,
    fps: o.fps,
    html,
    css,
    js,
    fields,
    settings,
    assets: [...o.importedImages, ...(o.customFont ? [o.customFont.asset] : [])],
    layers: [],
  };

  // Timeline v2: convert the emitted region into the NOACG_ANIM data block. The strip's fade
  // becomes ordinary keyframes; the measured travel rides across as a `dynamics` segment
  // naming its builder above (docs/DYNAMIC_MOTION_SCOPE.md). The builders themselves sit
  // outside the region and are untouched by the conversion.
  return convertToDataRegion(template);
}

/** The authoring API for ticker variant modules. */
export function defineTickerVariant(
  spec: Omit<TemplateVariant, 'create'>,
  meta: TickerMeta,
  buildDesign: (o: ResolvedOptions) => TickerDesign,
): TemplateVariant {
  const variant: TemplateVariant = {
    ...spec,
    create(options?: WizardOptions) {
      const o = resolveOptions(variant, options);
      return assembleTicker(meta, buildDesign(o), o);
    },
  };
  return variant;
}
