// Ticker scaffolding. Tickers are data-driven: a textarea field (f0) holds the items —
// one per line — f1 is the strip's label ("BREAKING", the show name…), and an OPTIONAL f2 is
// a second cap a design can put a topic, a source or a channel name in. The template's
// JS renders the items at runtime; the marquee preset needs them rendered TWICE for a
// seamless loop, so rebuildTicker() handles that automatically.
//
// THE TEXT FORMAT IS docs/TICKERS.md, and it has one mark: A COLON ENDS A KICKER. A ticker
// item is a story, optionally tagged with what it is about ("SPORT: United win 3-0"), and a
// kicker typed on its own line tags every story beneath it. The full rule set is on
// parseTickerItems below.
//
// Structure contract:
//   <div class="ticker">                root — positioned by zone; opacity:0 until play()
//     <div class="ticker-box">          the strip; presets fade this
//       [<div class="ticker-label"><span id="f1">…</span></div>]   optional label block
//       <div class="ticker-viewport">   overflow hidden window
//         <div id="ticker-track">       items injected by rebuildTicker()
//       </div>
//       [<div class="ticker-cap"><span id="f2">…</span></div>]     optional second cap
//     </div>
//     hidden #f0 source SPX writes into
//   </div>

import type { SpxField, SpxTemplate } from '../../model/types';
import { definitionScriptBlock } from '../../model/spxDefinition';
import { resolveEasing } from '../../model/easings';
import {
  resolveOptions,
  type ResolvedOptions,
  type TemplateVariant,
  type WizardOptions,
} from '../../model/wizard';
import {
  baseSettings,
  computeScale,
  dataSourceCss,
  documentHtml,
  ESCAPE_HTML_JS,
  resetCanvasCss,
  resolveHeadingFont,
  rootVarsCss,
  setFieldValueJs,
  zoneCssText,
} from '../shared/base';
import type { PresetConfig } from '../lowerThirds/animPresets';
import type { AnimData } from '../../blocks/animData';
import { convertToDataRegion } from '../shared/standard';
import { tickerPresetById } from './tickerPresets';
import { TICKER_MOTION_JS } from './tickerMotion';
import { resolveTokens, type ThemeTokens, type TokenOverrides } from '../../model/themeTokens';

export interface TickerDesign {
  /** Inner HTML of .ticker — must contain .ticker-box > .ticker-viewport > #ticker-track. */
  html: string;
  /** Variant CSS (strip, label, items, separators). */
  css: string;
  /** JS defining renderTickerItem(text) — the markup for one item (include your separator). */
  rowBuilderJs: string;
  /** Whether the marquee needs the items doubled for a seamless loop (flip designs don't). */
  doubleItems: boolean;
  /**
   * Where this design disagrees with its style family's shape tokens
   * (model/themeTokens.ts). Every entry is conformance debt - DESIGN_LANGUAGE §8's rule is
   * "reuse the exact token values, don't improvise new ones per category".
   */
  tokens?: TokenOverrides;
}

export interface TickerMeta {
  name: string;
  description: string;
  uicolor: string;
}

function tickerRuntimeJs(name: string, animationBlock: string): string {
  return `// ${name} — generated by NoaCG Studio. SPX calls update(), play(), stop(), next().

${ESCAPE_HTML_JS}

// parseTickerItems(text): the rundown is ONE block of plain text, and there is one mark to
// learn - A COLON ENDS A KICKER. Everything else is the story.
//
//   SPORT: United win 3-0     a story TAGGED with what it is about. The tag is the kicker.
//   SPORT:                    a kicker on its own line. Every story beneath it carries it,
//   United win 3-0            until a blank line or the next kicker - so a run of stories
//   City held at home         from one desk is typed once, not once per line.
//   SPORT <TAB> United win    the same, which is what a paste from a spreadsheet gives.
//   Storm warning issued      anything else is a plain story, with no kicker at all.
//   (blank line)              closes the open kicker.
//
// A semicolon is accepted wherever a colon is, for the same reason end credits accept one.
//
// NO PIPE, and that is a deliberate difference from docs/END_CREDITS.md: tk17 splits an item
// at "|" into its two LANGUAGES, and that design ships with bilingual samples. A mark already
// spoken for by a design cannot be given a second meaning by the parser above it.
//
// Nothing is required. A rundown with no marks at all is a plain list of stories, exactly as
// every ticker read before kickers existed - which is why no sample had to change.
//
// Values are escaped in tickerItemHtml() below rather than here, because a design's
// renderTickerKicked() is handed the two halves separately and must get them already safe.

// The longest text accepted BEFORE the colon as a kicker. A kicker is a tag; a headline is
// not. Without this, "The question everyone was asking was this:" becomes a tag.
var KICKER_LABEL_MAX = 32;

// tickerKickerMark(line): the index of the colon that ends the kicker, or -1 for none.
//
// The colon must be FOLLOWED BY A SPACE or by nothing at all. That is the second condition,
// and it is why this is not the credits rule verbatim: a ticker's own designs write
// "United 2:1 City" (tk13 lifts the n:n into a score chip), "Polling stations close at 20:00"
// and "Results from 21:00", and a length guard alone would have turned every one of those
// into a kicker. A tag is written with a space after its colon; a score and a clock are not.
function tickerKickerMark(line) {
  var mark = line.search(/[:;](?=\\s|$)/);
  return (mark > 0 && mark <= KICKER_LABEL_MAX) ? mark : -1;
}

function parseTickerItems(text) {
  var items = [];
  var open = '';                       // the kicker the following bare lines inherit

  text.split('\\n').forEach(function (raw) {
    var line = raw.trim();
    if (line === '') { open = ''; return; }        // blank line closes the open kicker

    // "SPORT<TAB>United win 3-0" - an explicit separator, so no length guard applies: the
    // operator has said outright which half is which.
    var tab = line.indexOf('\\t');
    if (tab > 0) {
      open = line.slice(0, tab).trim();
      var tabbed = line.slice(tab + 1).trim();
      if (tabbed) items.push({ kicker: open, text: tabbed });
      return;
    }

    // The colon rule, in ONE branch: text before the colon is the kicker, whatever follows it
    // on the same line is that kicker's first story. "SPORT:" simply has nothing after it,
    // which is what leaves the kicker open for the lines beneath.
    var mark = tickerKickerMark(line);
    if (mark > 0) {
      open = line.slice(0, mark).trim();
      var inline = line.slice(mark + 1).trim();
      if (inline) items.push({ kicker: open, text: inline });
      return;
    }

    items.push({ kicker: open, text: line });
  });
  return items;
}

// tickerItemHtml(item): one parsed item as markup.
//
// renderTickerItem() keeps its ONE argument, so every design kept working when kickers
// landed. The kicker rides INSIDE the item the design draws, ahead of the story, which is
// what makes it travel with it in a marquee and stack with it in a rotator. A design that
// places the tag itself - tk18 gives it a column of its own - defines
// renderTickerKicked(kicker, text) and is handed both halves.
//
// Escaped HERE rather than in each design's builder: the builders are the part a design
// rewrites, and the safety of the strip must not depend on remembering the rule.
//
// A BUILDER IS ONLY EVER HANDED THE STORY, never markup, and the tag is placed into what it
// returns. The kicker used to be concatenated ahead of the text and the whole string passed in,
// which works only while a builder treats its argument as opaque. Six of the twenty-two do not:
// tk04, tk06, tk13, tk14, tk17 and tk22 read their argument to find a delta, a score or a
// language break, so they matched their pattern against the SPAN instead of the story. On tk14
// "Market Board" the regex took the tag's markup for an instrument and split it at the space
// inside the class attribute, and the attribute itself aired as visible text - a viewer read
// class="ticker-kicker">OMXH25 across the strip (owner walk, 2026-08-28, reproduced with the
// rundown "OMXH25: 4218.60 +1.24%"). Placing the tag afterwards, through the DOM, makes it work
// identically on every design instead of on the ones that happen not to look at their argument.
//
// FIRST CHILD OF THE ITEM the builder drew - the same position the old string form produced for
// every design that was already right (all of them wrap the story in one element), and the
// right one for the six that were not: ahead of tk14's symbol, tk13's score chip, tk17's first
// language. A design that wants the tag somewhere else still defines renderTickerKicked(kicker,
// text) and is handed both halves - tk18 gives it a column of its own.
function tickerItemHtml(item) {
  var text = escapeHtml(item.text);
  if (!item.kicker) return renderTickerItem(text);
  var kicker = escapeHtml(item.kicker);
  if (typeof renderTickerKicked === 'function') return renderTickerKicked(kicker, text);
  var host = document.createElement('div');
  host.innerHTML = renderTickerItem(text);
  var drawn = host.firstElementChild;
  // A builder that returns bare text has no item to place the tag inside; the old spelling is
  // then exactly right, and it is the only case that still concatenates.
  if (!drawn) return '<span class="ticker-kicker">' + kicker + '</span>' + host.innerHTML;
  var tag = document.createElement('span');
  tag.className = 'ticker-kicker';
  tag.textContent = item.kicker;   // textContent escapes it - the same safety, done by the DOM
  drawn.insertBefore(tag, drawn.firstChild);
  return host.innerHTML;
}

// rebuildTicker(): re-render the items from the hidden #f0 source.
function rebuildTicker() {
  var track = document.getElementById('ticker-track');
  // A ROTATING ticker shows one item at a time and the graphic's own timer advances it, so
  // rendering the whole list here would both look wrong and pile every item into the strip at
  // once. Hand it back to the rotator instead.
  if (TICKER_ROTATE && typeof tickerShowNext === 'function') { tickerShowCurrent(); return; }
  var html = '';
  parseTickerItems(document.getElementById('f0').textContent).forEach(function (item) {
    html += tickerItemHtml(item);
  });
  // The marquee loop needs the set twice: sliding one set length reads as endless.
  track.innerHTML = TICKER_DOUBLE_ITEMS ? html + html : html;
}

${setFieldValueJs}

// update(data): SPX sends field values as JSON; the label (f1) is written straight into
// its element, the items (f0) into the hidden source — then the track re-renders.
function update(data) {
  var fields = (typeof data === 'string') ? JSON.parse(data) : data;
  for (var key in fields) {
    var el = document.getElementById(key);
    if (el) setFieldValue(el, fields[key]);
  }
  rebuildTicker();
}

// play(): rebuild (fresh measurements), then start the loop.
function play() {
  gsap.killTweensOf('*');
  rebuildTicker();
  buildInTimeline();
}

// stop(): take the ticker off air (also stops the loop).
function stop() {
  gsap.killTweensOf('*');
  buildOutTimeline();
}

// next(): SPX Continue — advance one step along the default path. This design ships
// single-step, so it normally does nothing; it still funnels to the interpreter so a
// template that GROWS a step (or a state machine) stays drivable through the SPX contract.
function next() {
  return (typeof revealNextStep === 'function') ? revealNextStep() : null;
}

// Render once on load so the preview shows content before the first update().
// This file loads in <head>, before the ticker elements exist — wait for the DOM.
if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', rebuildTicker);
} else {
  rebuildTicker();                // DOM already parsed (e.g. an inline preview build)
}

${animationBlock}
`;
}

/**
 * Rotating tickers show ONE item at a time, advanced by the graphic's own state machine.
 *
 * Every ticker design is built for the marquee: the track is one endless nowrap row that
 * TRAVELS past a clipping viewport, so a long story is fine — it scrolls by. A rotating strip
 * has nowhere to travel to, so the same markup would just push a long story off the end of the
 * strip and into whatever cap sits there. These rules turn the track back into an ordinary
 * block that fits its viewport and wraps, which is the auto-fit pattern used everywhere else.
 */
const ROTATE_CSS = `
/* ── Rotating strip: the item FITS the viewport instead of travelling past it. ── */

/* The viewport clips because a marquee's items have to vanish at the strip's edges. Nothing
   travels here, so clipping would only ever cut a wrapped story in half — let the strip grow
   to whatever the current item needs instead. */
.ticker-viewport {
  overflow: visible;
}

#ticker-track {
  display: block;                  /* not an endless row — one item, in normal flow */
  width: 100%;                     /* fill the space the caps leave */
  white-space: normal;             /* a long story wraps rather than running off the strip */
  will-change: opacity, transform; /* the machine's beat fades and lifts it */
}

.ticker-item {
  display: block;                  /* the item is the line, not a cell in a row */
  overflow-wrap: break-word;       /* break a very long unbroken word */
}

/* The separator punctuates a ROW of stories; a rotating strip shows one at a time. */
.ticker-sep {
  display: none;
}
`;

// The fallback rundown, for a design that declares no sample of its own. Two of the four are
// tagged and two are not, because that is what the format promises: a kicker is available on
// any item and required on none.
const ITEMS_SAMPLE = [
  'TONIGHT: Welcome to the live show',
  'NEXT WEEK: Guest lineup announced',
  'Send your questions with #ontheair',
  'Tickets for the summer tour are on sale now',
].join('\n');

/** Build the complete ticker SpxTemplate. */
export function assembleTicker(meta: TickerMeta, design: TickerDesign, o: ResolvedOptions,
  /** Refine the converted animation data — the seam a graphic TYPE injects its machine
   *  through (see shared/standard.ts composeRefine for the ordering rule). */
  refine?: (data: AnimData) => AnimData,
  /** The design's resolved SHAPE tokens (model/themeTokens.ts). Resolved by the caller,
   *  because the family lives on the VARIANT (styleTag) and this function only sees the
   *  design. Absent = emit no token lines, which is what every template did before they
   *  existed. */
  tokens?: ThemeTokens,
): SpxTemplate {
  const font = resolveHeadingFont(o);
  const scale = computeScale(o);

  const itemsText = o.lines[0]?.sample || ITEMS_SAMPLE;
  const labelText = o.lines[1]?.sample || 'ON AIR';
  const fields: SpxField[] = [
    { field: 'f0', ftype: 'textarea', title: o.lines[0]?.title || 'Ticker items', value: itemsText },
    { field: 'f1', ftype: 'textfield', title: o.lines[1]?.title || 'Label', value: labelText },
  ];
  // A THIRD line is optional and purely additive: a design that declares `maxLines: 3` gets a
  // second cap it can put anything in — a topic, a source, a channel name — and places the
  // `#f2` element itself. Every design that came before this declares two lines, so
  // `o.lines[2]` is absent for them and the emitted definition is byte-identical.
  if (o.lines[2]) {
    fields.push({ field: 'f2', ftype: 'textfield', title: o.lines[2].title, value: o.lines[2].sample });
  }

  const settings = baseSettings(meta, o, { steps: '1', playlayer: '3', webplayout: '3' });

  const html = documentHtml({
    title: meta.name,
    definitionBlock: definitionScriptBlock(settings, fields),
    body: `  <!-- ${meta.name}. Items are rendered by rebuildTicker() from the hidden source below. -->
  <div class="ticker">
${design.html}
    <!-- Hidden items source — SPX writes field f0 here; JS renders it. -->
    <div id="f0" class="noacg-data-source">${itemsText}</div>
  </div>`,
  });

  const css = `/* ${meta.name} — generated by NoaCG Studio. Edit freely: this file is yours. */

${rootVarsCss(o, font.stack, scale, { tokens, consumerCss: design.css })}

${font.face}

${resetCanvasCss(o.resolution)}

/* ── Root position (anchor zone) ── */
.ticker {
  position: absolute;
${zoneCssText(o.zone, o.nudge, o.resolution)}
  opacity: 0;                      /* hidden until play() runs the entrance */
}

/* ── Item kicker: the tag a story is filed under ("SPORT: United win 3-0"). ──
   Shared, and emitted BEFORE the design so a design that wants its own treatment simply
   restates the rule. Every ticker gets one for free, which is what makes the mark portable:
   the same rundown carries its tags into whichever design you switch to. */
.ticker-kicker {
  color: var(--accent);
  font-weight: 700;
  letter-spacing: 0.08em;
  text-transform: uppercase;
  margin-right: calc(10px * var(--scale));
}

/* ── Design ── */
${design.css}
${o.animation.presetId === 'ticker-rotate' ? ROTATE_CSS : ''}

${dataSourceCss}`;

  const preset = tickerPresetById(o.animation.presetId);
  const ease = resolveEasing(o.animation.easing, preset.autoEase);
  const cfg: PresetConfig = {
    prefix: 'ticker',
    lineCount: fields.length,
    hasAccent: false,
    steps: false,
    speed: o.animation.speed,
    easeIn: ease.easeIn,
    easeOut: ease.easeOut,
  };

  const js = tickerRuntimeJs(
    meta.name,
    `// Marquee designs render the items twice for a seamless loop; flip designs don't.
var TICKER_DOUBLE_ITEMS = ${o.animation.presetId === 'ticker-rotate' ? false : design.doubleItems};

// A ROTATING ticker shows one item at a time, advanced by the graphic's state machine rather
// than by endless motion — so the whole list never goes into the strip at once.
var TICKER_ROTATE = ${o.animation.presetId === 'ticker-rotate'};

${design.rowBuilderJs}

${TICKER_MOTION_JS}

${preset.emit(cfg)}`,
  );

  const template: SpxTemplate = {
    name: meta.name,
    type: 'ticker',
    resolution: o.resolution,
    fps: o.fps,
    html,
    css,
    js,
    fields,
    settings,
    assets: [...o.importedImages, ...(o.customFont ? [o.customFont.asset] : [])],
    layers: [],
  };

  // Timeline v2: convert the emitted region into the NOACG_ANIM data block. The strip's fade
  // becomes ordinary keyframes; the measured travel rides across as a `dynamics` segment
  // naming its builder above (docs/DYNAMIC_MOTION_SCOPE.md). The builders themselves sit
  // outside the region and are untouched by the conversion.
  return convertToDataRegion(template, refine);
}

/** The authoring API for ticker variant modules. */
export function defineTickerVariant(
  spec: Omit<TemplateVariant, 'create'>,
  meta: TickerMeta,
  buildDesign: (o: ResolvedOptions) => TickerDesign,
  /** Optional animation-data refinement (a graphic type's machine rides in here). It is
   *  built per create() because a type's compiled machine depends on the resolved options. */
  refine?: (o: ResolvedOptions) => ((data: AnimData) => AnimData) | undefined,
): TemplateVariant {
  const variant: TemplateVariant = {
    ...spec,
    create(options?: WizardOptions) {
      const o = resolveOptions(variant, options);
      const design = buildDesign(o);
      // The family lives on the variant, the overrides on the design — resolved here
      // because this is the only place that holds both.
      const tokens = resolveTokens(spec.styleTag, design.tokens);
      return assembleTicker(meta, design, o, refine?.(o), tokens);
    },
  };
  return variant;
}
