// CasparCG export: one SELF-CONTAINED HTML file — CasparCG's `CG ADD … "name"` loads
// templates/<name>.html directly, so everything (CSS, GSAP, template JS, images, fonts)
// is inlined into a single file. A small data shim on top of the template's update()
// accepts both JSON strings and CasparCG's classic XML templateData format, so the
// template works with any CasparCG client out of the box.

import JSZip from 'jszip';
import type { SpxTemplate } from '../../model/types';
import { composeSelfContainedHtml } from '../selfContained';
import { slug } from '../common';
import type { ExportTarget } from '../registry';

// Wraps the template's own update() so CasparCG XML payloads work too. Teachable ES5,
// same voice as the generated template code.
const CASPAR_DATA_SHIM = `// ── CasparCG data shim ────────────────────────────────────────────────────
// CasparCG clients send template data either as JSON ({"f0":"…"}) or as XML:
//   <templateData><componentData id="f0"><data id="text" value="…"/></componentData>…
// This wrapper converts the XML form into the JSON form the template understands.
(function () {
  var jsonUpdate = window.update;
  window.update = function (raw) {
    if (typeof raw === 'string' && raw.replace(/^\\s+/, '').charAt(0) === '<') {
      var fields = {};
      var doc = new DOMParser().parseFromString(raw, 'text/xml');
      var components = doc.getElementsByTagName('componentData');
      for (var i = 0; i < components.length; i++) {
        var id = components[i].getAttribute('id');
        var data = components[i].getElementsByTagName('data')[0];
        if (id && data) fields[id] = data.getAttribute('value') || '';
      }
      jsonUpdate(JSON.stringify(fields));
    } else {
      jsonUpdate(raw);
    }
  };
})();`;

/** Build the single-file HTML: strip external refs, inline everything (shared composer). */
export function composeCasparHtml(template: SpxTemplate): string {
  return composeSelfContainedHtml(template, [CASPAR_DATA_SHIM]);
}

export const casparTarget: ExportTarget = {
  id: 'casparcg',
  label: 'CasparCG export',
  description: 'One self-contained .html file (CSS, JS, GSAP, images inlined) + a data shim for CasparCG XML payloads.',
  async build(template) {
    const zip = new JSZip();
    const name = slug(template.name);
    const root = zip.folder(name)!;
    root.file(`${name}.html`, composeCasparHtml(template));
    root.file(
      'README.md',
      `# ${template.name} — CasparCG template\n\nGenerated by NoaCG Studio.\n\n` +
        `Copy ${name}.html into your CasparCG templates folder and load it with:\n\n` +
        `    CG 1-20 ADD 1 "${name}" 1 "<templateData>…</templateData>"\n\n` +
        `Data works as JSON ({"f0":"…"}) or CasparCG XML componentData — both reach the\n` +
        `template's update(). play()/stop()/next() are the standard CasparCG invokes.\n` +
        `Everything is inlined: no other files are needed at playout.\n`,
    );
    return zip;
  },
};
