// CasparCG export: one SELF-CONTAINED HTML file — CasparCG's `CG ADD … "name"` loads
// templates/<name>.html directly, so everything (CSS, GSAP, template JS, images, fonts)
// is inlined into a single file. A small data shim on top of the template's update()
// accepts both JSON strings and CasparCG's classic XML templateData format, so the
// template works with any CasparCG client out of the box.
//
// The package also carries controlpanel.html and the receiver that answers it, the way the SPX
// folder package and the HTML-overlay package do. A CasparCG server drives the graphic through
// its own client and needs none of that — but the package is also what a room falls back to when
// the playout machine or the network is gone, and served over one http address in one browser
// the panel is then the only operator surface left. It was missing until 2026-09-04, which made
// the standalone panel unreachable from a CasparCG package for EVERY graphic, imported or catalog
// (docs/backlog/exported-panel-does-not-pair-with-an-imported-design.md).

import JSZip from 'jszip';
import type { SpxTemplate } from '../../model/types';
import { composeSelfContainedHtml } from '../selfContained';
import { addControlPanel, injectControlReceiver, slug } from '../common';
import { onAirGuideMd } from '../onAirGuide';
import { casparClientStepsMd, dataFields, fieldReferenceMd } from '../fieldReference';
import type { ExportContext, ExportTarget } from '../registry';

// Wraps the template's own update() so CasparCG XML payloads work too. Teachable ES5,
// same voice as the generated template code.
const CASPAR_DATA_SHIM = `// ── CasparCG data shim ────────────────────────────────────────────────────
// CasparCG clients send template data either as JSON ({"f0":"…"}) or as XML:
//   <templateData><componentData id="f0"><data id="text" value="…"/></componentData>…
// This wrapper converts the XML form into the JSON form the template understands.
(function () {
  var jsonUpdate = window.update;
  window.update = function (raw) {
    if (typeof raw === 'string' && raw.replace(/^\\s+/, '').charAt(0) === '<') {
      var fields = {};
      var doc = new DOMParser().parseFromString(raw, 'text/xml');
      var components = doc.getElementsByTagName('componentData');
      for (var i = 0; i < components.length; i++) {
        var id = components[i].getAttribute('id');
        var data = components[i].getElementsByTagName('data')[0];
        if (id && data) fields[id] = data.getAttribute('value') || '';
      }
      jsonUpdate(JSON.stringify(fields));
    } else {
      jsonUpdate(raw);
    }
  };
})();`;

/** Build the single-file HTML: strip external refs, inline everything (shared composer).
 *  The control receiver lands first (it goes in before `</body>`, and the composer appends the
 *  template's own JS after it), so the bundled panel has something to answer it. */
export function composeCasparHtml(template: SpxTemplate): Promise<string> {
  return composeSelfContainedHtml(
    { ...template, html: injectControlReceiver(template.html, template) },
    [CASPAR_DATA_SHIM],
  );
}

export const casparTarget: ExportTarget = {
  id: 'casparcg',
  label: 'CasparCG export',
  description:
    'One self-contained .html file (CSS, JS, GSAP, images inlined) + a data shim for CasparCG XML payloads. Includes a control panel for the days there is no playout machine.',
  successMessage: '✓ Exported. Drop the .html into your CasparCG templates folder.',
  async build(template, ctx?: ExportContext) {
    const zip = new JSZip();
    const name = slug(template.name);
    const root = zip.folder(name)!;
    // The graphic's OWN declared layer, not a fixed 20: a production package gives each of its
    // graphics a distinct layer, and a copy-paste line naming the wrong one puts two templates
    // on top of each other — the exact eviction the per-graphic layers were introduced to stop.
    const layer = Number(template.settings.playlayer) || 1;
    root.file(`${name}.html`, await composeCasparHtml(template));
    root.file(
      'README.md',
      `# ${template.name} — CasparCG template\n\nGenerated by NoaCG Studio.\n\n` +
        `Copy ${name}.html into your CasparCG templates folder and load it with:\n\n` +
        `    CG 1-${layer} ADD 1 "${name}" 1 "<templateData>…</templateData>"\n\n` +
        `Data works as JSON ({"f0":"…"}) or CasparCG XML componentData — both reach the\n` +
        `template's update(). play()/stop()/next() are the standard CasparCG invokes.\n` +
        `Everything is inlined: no other files are needed at playout.\n\n` +
        `**FIELDS.md** lists every field with the ID your client sends it under (f0, f1, …).\n\n` +
        `**controlpanel.html** is the fallback operator page — for the day the playout machine\n` +
        `is not there. It drives the graphic over a same-origin browser channel, so it works\n` +
        `when BOTH pages are opened from the same web address (http:// or https://, same host\n` +
        `and port) in the same browser. It cannot reach a graphic loaded by CasparCG itself:\n` +
        `that runs its own browser engine, and there your CasparCG client is the controller.\n` +
        `See GETTING-ON-AIR.md.\n`,
    );
    // The ID table is the file a CasparCG operator keeps open: the client speaks ids, and only
    // this package can say which id is the title and which is the name. It carries the CLIENT's
    // own walkthrough (the official CasparCG Client), because a student who has never sent a CG
    // command cannot turn `CG 1-20 ADD …` into "which box do I type the name in".
    root.file(
      'FIELDS.md',
      fieldReferenceMd(template, casparClientStepsMd(name, layer, dataFields(template))),
    );
    // This package is ONE graphic file: there is no images/ folder beside the panel, so its
    // picker sends the embedded bytes rather than a path that resolves at neither end — the
    // same reasoning as the HTML-overlay target's.
    addControlPanel(root, template, { inlineAssets: true, entries: ctx?.entries });
    root.file('GETTING-ON-AIR.md', onAirGuideMd({ controlPanel: 'controlpanel.html' }));
    return zip;
  },
};
