// H2R Graphics export: one SELF-CONTAINED HTML file for H2R's "Custom HTML" graphic type
// (https://h2r.graphics/docs/graphics/custom-html/). H2R imports the .html, shows editable
// inputs from a GDD block (<script type="application/json+gdd">, properties keyed by
// element id), calls update(json) with the changed values, and calls play() BOTH when the
// graphic comes on air and when it goes off air — so a small toggle shim turns that into
// the template's own play()/stop() pair.

import JSZip from 'jszip';
import type { SpxField, SpxTemplate } from '../../model/types';
import { composeSelfContainedHtml } from '../selfContained';
import { slug } from '../common';
import type { ExportTarget } from '../registry';

/** Map one SPX DataField to a GDD property (H2R's editable-input schema). The shape mirrors
 *  the working Loopic → H2R sample (type + label + description + default + gddType). */
function gddProperty(field: SpxField): Record<string, unknown> {
  const base = { type: 'string', label: field.title || field.field, description: field.title || '', default: field.value ?? '' };
  switch (field.ftype) {
    case 'textarea':
      return { ...base, gddType: 'multi-line' };
    case 'number':
      return { type: 'number', label: base.label, description: base.description, default: Number(field.value) || 0 };
    case 'filelist':
      // An image/file path — a plain single-line input the operator types/pastes the path
      // into; the value lands in the <img id="fN">. (No 'file-path' gddType: H2R skips
      // properties whose gddType it doesn't recognize.)
      return { ...base, gddType: 'single-line' };
    default:
      return { ...base, gddType: 'single-line' };
  }
}

/** The GDD block H2R parses into editable inputs (property key = element id). */
export function gddScript(template: SpxTemplate): string {
  const gdd = {
    $schema: 'https://superflytv.github.io/GraphicsDataDefinition/gdd-meta-schema/v1/schema.json',
    title: template.name,
    description: `${template.name} — generated by NoaCG Studio`,
    type: 'object',
    properties: Object.fromEntries(template.fields.map((f) => [f.field, gddProperty(f)])),
  };
  // The script tag MUST carry name="graphics-data-definition": that is how H2R (and the
  // SuperflyTV GDD tooling) discovers the block. Without the name attribute H2R silently
  // shows no editable fields — verified against H2R's own Loopic-exported sample.
  return `  <!-- GDD (Graphics Data Definition): H2R Graphics reads this into editable inputs.
       Each property key matches the element id the value is written into (f0, f1, …). -->
  <script name="graphics-data-definition" type="application/json+gdd">
${JSON.stringify(gdd, null, 2)}
  </script>
`;
}

// H2R calls play() both ways and never calls stop(); convert the toggle into the pair.
const H2R_TOGGLE_SHIM = `// ── H2R on/off toggle ─────────────────────────────────────────────────────
// H2R Graphics runs the global play() BOTH when the graphic comes on air and
// when it goes off air (it never calls stop()). This wrapper turns that toggle
// into the template's own play()/stop() pair. Remove it if you drive the file
// from something that calls play() and stop() separately.
(function () {
  var entrance = window.play;
  var exit = window.stop;
  var onAir = false;
  window.play = function () {
    onAir = !onAir;
    if (onAir) entrance(); else exit();
  };
})();`;

function h2rReadme(template: SpxTemplate): string {
  const name = slug(template.name);
  const multiStep = template.settings.steps !== '1';
  return `# ${template.name} — H2R Graphics custom graphic

Generated by NoaCG Studio.

One self-contained file: ${name}.html — CSS, JS, GSAP, fonts and images are all inlined.

## Install (H2R Graphics v3+)
1. Add a graphic → **Custom HTML**.
2. Import ${name}.html into the graphic's content.
3. The fields below appear as editable inputs (from the embedded GDD definition).
4. Take it on air — H2R runs the entrance; taking it off air runs the exit.

## Data fields
${template.fields.map((f) => `- ${f.field} (${f.ftype}): ${f.title}`).join('\n') || '- (none)'}

## Notes
- H2R calls play() for BOTH on-air and off-air; a small marked "H2R on/off toggle" block at
  the end of the file converts that into this template's play()/stop() pair.
${multiStep ? `- This template is multi-step (SPX Continue). H2R has no next() call, so all steps show
  according to the entrance timeline only — re-export with steps off for H2R use.
` : ''}- Everything is inlined — no other files are needed.
`;
}

export const h2rTarget: ExportTarget = {
  id: 'h2r',
  label: 'H2R Graphics export',
  description:
    'One self-contained .html for H2R\'s Custom HTML graphic type — fields become editable H2R inputs (embedded GDD), on/off drives the entrance and exit.',
  successMessage: '✓ Exported. Add the .html as an H2R Custom HTML graphic (see README.md).',
  async build(template) {
    const zip = new JSZip();
    const name = slug(template.name);
    const root = zip.folder(name)!;
    // The GDD block rides in <head>; the toggle shim lands after the template JS.
    const withGdd = {
      ...template,
      html: /<\/head>/i.test(template.html)
        ? template.html.replace(/<\/head>/i, `${gddScript(template)}</head>`)
        : gddScript(template) + template.html,
    };
    root.file(`${name}.html`, composeSelfContainedHtml(withGdd, [H2R_TOGGLE_SHIM]));
    root.file('README.md', h2rReadme(template));
    return zip;
  },
};
