// HTML overlay export: one SELF-CONTAINED HTML file for plain browser-source playout —
// OBS Browser Source, vMix Web Browser input, or any tool that renders a web page over
// video. Unlike SPX/CasparCG there is no playout server to call the globals, so the file
// autoplays on load: it fills the fields (values baked from the Data panel at export time,
// falling back to the SPX definition's defaults) and calls play(). The BroadcastChannel
// control receiver + the bundled controlpanel.html let an operator drive it live.

import JSZip from 'jszip';
import type { SpxTemplate } from '../../model/types';
import { composeSelfContainedHtml } from '../selfContained';
import { injectControlReceiver, addControlPanel, slug } from '../common';
import { hasRealtimeControl } from '../../control/realtimeControl';
import type { ExportContext, ExportTarget } from '../registry';

/** The autoplay block appended after the template's JS. Teachable ES5, same voice as the
 *  generated template code. `baked` carries the Data panel's values at export time. */
function autoplayScript(baked: Record<string, string>): string {
  return `// ── Autoplay for browser sources (OBS / vMix) ────────────────────────────
// A playout server (SPX, CasparCG) calls update() and play() itself. A plain
// browser source has no operator, so this block does it on page load: fill the
// fields with the values below (baked in at export time; any field missing
// there falls back to its default in the SPX definition), then start the
// graphic. Edit the values here or drive them live with controlpanel.html.
(function () {
  var baked = ${JSON.stringify(baked, null, 2).replace(/\n/g, '\n  ')};
  function startData() {
    var data = {};
    var def = window.SPXGCTemplateDefinition || {};
    var fields = def.DataFields || [];
    for (var i = 0; i < fields.length; i++) {
      var f = fields[i];
      if (!f.field) continue;
      data[f.field] = baked[f.field] !== undefined ? baked[f.field] : (f.value || '');
    }
    return data;
  }
  window.addEventListener('load', function () {
    if (typeof window.update === 'function') window.update(JSON.stringify(startData()));
    if (typeof window.play === 'function') window.play();
  });
})();`;
}

function overlayReadme(template: SpxTemplate): string {
  const name = slug(template.name);
  return `# ${template.name} — HTML overlay (OBS / vMix / any browser source)

Generated by NoaCG Studio.

One self-contained file: ${name}.html — CSS, JS, GSAP, fonts and images are all inlined.
The background is transparent, so it composites straight over your video. On load it fills
the fields with the exported values and plays automatically.

## OBS Studio
1. Sources → + → **Browser**.
2. Tick **Local file** and pick ${name}.html.
3. Width ${template.resolution.width}, Height ${template.resolution.height}. Done — it plays on load.

## vMix
1. Add Input → **More** → **Web Browser**.
2. URL: the full path to ${name}.html (e.g. file:///C:/overlays/${name}.html).
3. Width ${template.resolution.width}, Height ${template.resolution.height}. Use it like any input (usually on an overlay channel).

## Changing the text/data
- Quick edit: open ${name}.html in a text editor — the values live in the marked
  "Autoplay for browser sources" block at the bottom.
- Live control: open controlpanel.html in another tab of the SAME browser as the graphic —
  edits + Play/Stop/Update/Next drive it over a BroadcastChannel, no server needed.
  In OBS you can add controlpanel.html as a custom dock (View → Docks → Custom Browser
  Docks…) to drive the source from inside OBS.
${hasRealtimeControl(template.js) ? `- Remote control (enabled): this graphic also listens on a Supabase Realtime channel, so
  controlpanel.html works from ANOTHER device too. The channel topic baked into both files
  is a shared secret — keep it private. The machine running the overlay must be allowed to
  reach wss://*.supabase.co.
` : `- Any-device control: enable **Remote control** in the Control tab before exporting and the
  control panel can drive the graphic from another device over the cloud.
`}
## Data fields
${template.fields.map((f) => `- ${f.field} (${f.ftype}): ${f.title}`).join('\n') || '- (none)'}

Everything is inlined — no other files are needed at playout.
`;
}

export const htmlOverlayTarget: ExportTarget = {
  id: 'html-overlay',
  label: 'HTML overlay (OBS / vMix)',
  description:
    'One self-contained .html that autoplays as a browser source — OBS, vMix, or any tool that renders a web page. Includes a control panel for live edits.',
  successMessage: '✓ Exported. Unzip and add the .html as a browser source (see README.md).',
  async build(template, ctx?: ExportContext) {
    const zip = new JSZip();
    const name = slug(template.name);
    const root = zip.folder(name)!;
    // Receiver first (it lands before </body>), then the compose inlines everything and
    // appends the autoplay block after the template JS.
    const withReceiver = { ...template, html: injectControlReceiver(template.html, template) };
    root.file(`${name}.html`, composeSelfContainedHtml(withReceiver, [autoplayScript(ctx?.sampleData ?? {})]));
    addControlPanel(root, template);
    root.file('README.md', overlayReadme(template));
    return zip;
  },
};
