// End-credits scaffolding. Credits are data-driven: one textarea field (f0) holds the whole
// credit list — "Role | Name" per line, a line WITHOUT a pipe is a section heading, a blank
// line starts a new section — and f1 holds the year/copyright line. The template's JS parses
// that text into rows at runtime, so operators edit credits without touching code.
//
// Structure contract:
//   <div class="credits">                 root — positioned by zone; opacity:0 until play()
//     <div class="credits-box">           the viewport (overflow hidden); presets fade this
//       <div id="credits-track">          rows injected by rebuildCredits()
//     </div>
//     hidden #f0 / #f1 sources SPX writes into
//   </div>
// Every track ends with the .credits-end block: logo placeholder + year (per the brief).

import type { SpxField, SpxTemplate } from '../../model/types';
import { definitionScriptBlock } from '../../model/spxDefinition';
import { resolveEasing } from '../../model/easings';
import {
  resolveOptions,
  type ResolvedOptions,
  type TemplateVariant,
  type WizardOptions,
} from '../../model/wizard';
import {
  baseSettings,
  computeScale,
  documentHtml,
  resetCanvasCss,
  resolveHeadingFont,
  rootVarsCss,
  setFieldValueJs,
  zoneCssText,
} from '../shared/base';
import type { PresetConfig } from '../lowerThirds/animPresets';
import { convertToDataRegion } from '../shared/standard';
import { creditsPresetById } from './creditsPresets';
import { CREDITS_MOTION_JS } from './creditsMotion';

export interface CreditsDesign {
  /** Inner HTML of .credits — must contain .credits-box > #credits-track. */
  html: string;
  /** Variant CSS (.credits-box sizing, row styles, end-block styles). */
  css: string;
  /**
   * JS defining renderCreditRow(entry) and renderEndBlock(yearHtml, logoSrc) — the
   * variant's row markup. entry = { type: 'heading'|'credit', role, name, text }.
   */
  rowBuilderJs: string;
}

export interface CreditsMeta {
  name: string;
  description: string;
  uicolor: string;
}

/** The shared runtime: parse the credits text and rebuild the track (outside the markers). */
function creditsRuntimeJs(name: string, animationBlock: string): string {
  return `// ${name} — generated by NoaCG Studio. SPX calls update(), play(), stop(), next().

${setFieldValueJs}

// parseCredits(text): each line "Role | Name" becomes a credit row; a line without "|"
// becomes a section heading; a blank line starts a new section.
function parseCredits(text) {
  var sections = [];
  var current = [];
  text.split('\\n').forEach(function (raw) {
    var line = raw.trim();
    if (line === '') {                       // blank line -> new section
      if (current.length) { sections.push(current); current = []; }
      return;
    }
    var parts = line.split('|');
    if (parts.length >= 2) {
      current.push({ type: 'credit', role: parts[0].trim(), name: parts.slice(1).join('|').trim() });
    } else {
      current.push({ type: 'heading', text: line });
    }
  });
  if (current.length) sections.push(current);
  return sections;
}

// rebuildCredits(): re-render the track from the hidden #f0 / #f1 / #f2 sources.
function rebuildCredits() {
  var track = document.getElementById('credits-track');
  var text = document.getElementById('f0').textContent;
  var year = document.getElementById('f1').textContent;
  // The end-of-credits logo is the image field f2 — a path like "images/logo.png".
  // Empty means "no logo picked yet": the design shows its styled placeholder instead.
  var logo = document.getElementById('f2').textContent.trim() || null;
  var html = '';
  parseCredits(text).forEach(function (section) {
    html += '<div class="credits-page">';     // one block per section (pages preset uses these)
    section.forEach(function (entry) { html += renderCreditRow(entry); });
    html += '</div>';
  });
  html += renderEndBlock(year, logo);
  track.innerHTML = html;
}

// update(data): SPX sends field values as JSON; write them into the hidden sources,
// then rebuild the visible rows.
function update(data) {
  var fields = (typeof data === 'string') ? JSON.parse(data) : data;
  for (var key in fields) {
    var el = document.getElementById(key);
    if (el) setFieldValue(el, fields[key]);
  }
  rebuildCredits();
}

// play(): rebuild (fresh measurements), then run the motion.
function play() {
  gsap.killTweensOf('*');
  rebuildCredits();
  buildInTimeline();
}

// stop(): take the credits off air.
function stop() {
  gsap.killTweensOf('*');
  buildOutTimeline();
}

// next(): SPX Continue — advance one step along the default path. This design ships
// single-step, so it normally does nothing; it still funnels to the interpreter so a
// template that GROWS a step (or a state machine) stays drivable through the SPX contract.
function next() {
  return (typeof revealNextStep === 'function') ? revealNextStep() : null;
}

// Render once on load so the preview shows content before the first update().
// This file loads in <head>, before the credit elements exist — wait for the DOM.
if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', rebuildCredits);
} else {
  rebuildCredits();               // DOM already parsed (e.g. an inline preview build)
}

${animationBlock}
`;
}

const CREDITS_SAMPLE = [
  'PRODUCTION',
  'Director | Alex Rivera',
  'Producer | Sam Chen',
  '',
  'CAMERA',
  'Director of Photography | Maria Santos',
  'Camera Operator | Jonas Berg',
  '',
  'Special thanks to everyone who made this show possible',
].join('\n');

/** Build the complete end-credits SpxTemplate. */
export function assembleCredits(meta: CreditsMeta, design: CreditsDesign, o: ResolvedOptions): SpxTemplate {
  const font = resolveHeadingFont(o);
  const scale = computeScale(o);

  // Credits fields: the multi-line credit list, the year line, and the end-block logo
  // (an SPX image field — the operator picks a file from the project's images/ folder).
  const creditsText = o.lines[0]?.sample || CREDITS_SAMPLE;
  const yearText = o.lines[1]?.sample || '© 2026 Your Production';
  const logoPath = o.logoAssetPath ?? '';
  const fields: SpxField[] = [
    { field: 'f0', ftype: 'textarea', title: o.lines[0]?.title || 'Credits', value: creditsText },
    { field: 'f1', ftype: 'textfield', title: o.lines[1]?.title || 'Year / copyright', value: yearText },
    { field: 'f2', ftype: 'filelist', title: 'Logo', value: logoPath, assetfolder: './images/', extension: 'png' },
  ];

  const settings = baseSettings(meta, o, { steps: '1', playlayer: '4', webplayout: '4' });

  const html = documentHtml({
    title: meta.name,
    definitionBlock: definitionScriptBlock(settings, fields),
    body: `  <!-- ${meta.name}. Rows are built by rebuildCredits() from the hidden sources below. -->
  <div class="credits">
${design.html}
    <!-- Hidden data sources — SPX writes the field values here; JS renders them. -->
    <div id="f0" style="display: none">${creditsText}</div>
    <div id="f1" style="display: none">${yearText}</div>
    <div id="f2" style="display: none">${logoPath}</div>
  </div>`,
  });

  const css = `/* ${meta.name} — generated by NoaCG Studio. Edit freely: this file is yours. */

${rootVarsCss(o, font.stack, scale)}

${font.face}

${resetCanvasCss(o.resolution)}

/* ── Root position (anchor zone) ── */
.credits {
  position: absolute;
${zoneCssText(o.zone, o.nudge, o.resolution)}
  opacity: 0;                      /* hidden until play() runs the entrance */
}

/* ── Design ── */
${design.css}
`;

  const preset = creditsPresetById(o.animation.presetId);
  const ease = resolveEasing(o.animation.easing, preset.autoEase);
  const cfg: PresetConfig = {
    prefix: 'credits',
    lineCount: 2,
    hasAccent: false,
    steps: false,
    speed: o.animation.speed,
    easeIn: ease.easeIn,
    easeOut: ease.easeOut,
  };

  const js = creditsRuntimeJs(
    meta.name,
    `${design.rowBuilderJs}\n\n${CREDITS_MOTION_JS}\n\n${preset.emit(cfg)}`,
  );

  const template: SpxTemplate = {
    name: meta.name,
    type: 'end-credits',
    resolution: o.resolution,
    fps: o.fps,
    html,
    css,
    js,
    fields,
    settings,
    assets: [...o.importedImages, ...(o.customFont ? [o.customFont.asset] : [])],
    layers: [],
  };

  // Timeline v2: convert the emitted region into the NOACG_ANIM data block. The box's fade
  // becomes ordinary keyframes; the measured travel rides across as a `dynamics` segment
  // naming its builder above (docs/DYNAMIC_MOTION_SCOPE.md). The builders themselves sit
  // outside the region and are untouched by the conversion.
  return convertToDataRegion(template);
}

/** The authoring API for end-credits variant modules. */
export function defineCreditsVariant(
  spec: Omit<TemplateVariant, 'create'>,
  meta: CreditsMeta,
  buildDesign: (o: ResolvedOptions) => CreditsDesign,
): TemplateVariant {
  const variant: TemplateVariant = {
    ...spec,
    create(options?: WizardOptions) {
      const o = resolveOptions(variant, options);
      return assembleCredits(meta, buildDesign(o), o);
    },
  };
  return variant;
}
