// Compose THIS checkout's .env.bench.local from the MAIN checkout's .env plus the per-harness
// configuration root .env does not carry. Secrets are copied file-to-file and never printed.
//
//   node scripts/bench-env.mjs --profile=lite [--model=<provider/model>] [--prompt-version=<id>]
//   node scripts/bench-env.mjs --profile=pro
//   [--user=<email>] [--ids=<uuid,uuid>]   (either profile: whose quota override to write)
//
// A linked worktree has no .env of its own, so this is the step that makes a paid round
// runnable from anywhere. See scripts/lite-eval-paths.mjs for why the target is named
// `.env.bench.local` and not `.env` or `.env.bench`.
//
// ONE composer for every harness on purpose: the Lite round had a bespoke one, the Pro round
// had none, and "which variables does this harness need" was answered from memory each time.

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { benchEnvPath, mainCheckout, mainEnv } from './lite-eval-paths.mjs';
import { defaultEvalEmail, resolveUserId } from './lite-eval-token.mjs';

const PROFILES = ['lite', 'pro'];

const argv = process.argv.slice(2);
const flag = (name) => argv.find((a) => a.startsWith(`--${name}=`))?.slice(name.length + 3);

const PROFILE = flag('profile') ?? 'lite';
if (!PROFILES.includes(PROFILE)) {
  console.error(`--profile must be one of ${PROFILES.join(', ')} (got "${PROFILE}").`);
  process.exit(1);
}
const MODEL = flag('model') ?? 'google/gemini-2.5-flash-lite';
const PROMPT_VERSION = flag('prompt-version') ?? '';
const src = mainEnv();

const need = (name, ...alternates) => {
  for (const key of [name, ...alternates]) {
    if (src[key]) return src[key];
  }
  console.error(`${mainCheckout()}/.env has no ${name}`);
  process.exit(1);
};

/** Present in root .env or not written at all - an empty value would OVERRIDE a real one. */
const optional = (name) => (src[name] ? [`${name}=${src[name]}`] : []);

// The override lifts the per-user daily/monthly Lite caps to 10,000 and concurrency to 2; the
// fleet daily spend ceiling stays the only control. The ids are resolved from the auth
// directory rather than hard-coded, so this works for whichever account holds the eval token
// and no account identifier is committed to an open repo.
let overrideIds = flag('ids') ?? src.AI_LITE_OVERRIDE_USER_IDS ?? '';
if (!overrideIds && PROFILE === 'lite') {
  const email = flag('user') ?? defaultEvalEmail();
  try {
    overrideIds = await resolveUserId(email);
  } catch (error) {
    console.error(`Could not resolve the eval user id: ${error.message}`);
    console.error('Pass --ids=<uuid,uuid> to skip the lookup.');
    process.exit(1);
  }
}

const OUT = benchEnvPath();
// A token stamped earlier is still valid; recomposing the configuration must not silently
// throw the identity away and leave the round runner reporting a missing token.
const carriedToken = existsSync(OUT)
  ? readFileSync(OUT, 'utf8')
      .replace(/^\uFEFF/, '')
      .split(/\r?\n/)
      .find((line) => line.startsWith('NOACG_LITE_EVAL_BEARER_TOKEN='))
  : undefined;

const lines = [
  `# Generated by scripts/bench-env.mjs --profile=${PROFILE} for a paid round in this checkout.`,
  '# Gitignored, local only, safe to delete. Read by `vite --mode bench` (npm run dev:bench)',
  '# - NOT by the e2e suite.',
  '',
  `AI_GATEWAY_API_KEY=${need('AI_GATEWAY_API_KEY')}`,
  `AI_KEY_ENCRYPTION_SECRET=${need('AI_KEY_ENCRYPTION_SECRET')}`,
  '# Every managed route this project funds is audited ZDR-served (docs/MODEL_ROUTE_AUDITS.md);',
  '# a bench that dropped the requirement would not be measuring what production serves.',
  'AI_SURFACE_REQUIRE_ZDR=1',
  '',
  `VITE_SUPABASE_URL=${need('VITE_SUPABASE_URL', 'SUPABASE_URL')}`,
  `VITE_SUPABASE_ANON_KEY=${need('VITE_SUPABASE_ANON_KEY', 'SUPABASE_ANON_KEY')}`,
  `SUPABASE_SERVICE_ROLE_KEY=${need('SUPABASE_SERVICE_ROLE_KEY', 'SUPABASE_SECRET_KEY')}`,
  // The Pro bench signs the browser in as the dedicated test account, because a managed key
  // only counts for a signed-in caller once a backend is configured.
  ...optional('E2E_EMAIL'),
  ...optional('E2E_PASSWORD'),
];

if (PROFILE === 'lite') {
  lines.push(
    // liteLedgerConfigured() requires a salt of at least 16 characters or Lite answers
    // `not-configured` with everything else correct. It salts the ANONYMOUS per-IP quota hash
    // only; an eval round is identity-bound, so a fixed local value changes nothing but the
    // ip_hash column. Root .env has none, which is why a local one is written here.
    'IP_HASH_SALT=noacg-local-lite-eval-salt',
    '',
    '# A bench round is NOT production traffic, and the ledger it writes to is. Without this the',
    '# bench server books every generation into the PRODUCTION ai_generations table, which cost',
    '# the 2026-08-13 matrix round its first attempt: 8 of 8 failed `ledger_update` because a',
    '# migration the code needed had not reached prod yet (docs/AI_LITE_BRAND_PLAN.md 4.4). The',
    '# in-memory store is refused outright when NODE_ENV=production or VERCEL=1, so this cannot',
    '# follow the configuration anywhere it would matter.',
    'AI_LITE_EVAL_MEMORY_LEDGER=1',
    '',
    '# Lite, configured exactly as production is: the same primary and second attempt, and the',
    '# same audited gateway provider slug (docs/MODEL_ROUTE_AUDITS.md - gemini-2.5-flash-lite is',
    '# served by vertex under ZDR). The route price comes from the approved-route catalog, so no',
    '# AI_LITE_PRICING_JSON is needed.',
    'AI_LITE_ENABLED=1',
    'AI_LITE_PRIMARY_PROVIDER=vercel',
    `AI_LITE_PRIMARY_MODEL=${MODEL}`,
    'AI_LITE_FALLBACK_PROVIDER=vercel',
    `AI_LITE_FALLBACK_MODEL=${MODEL}`,
    'AI_LITE_GATEWAY_PROVIDERS=vertex',
    'AI_LITE_REQUIRE_ZDR=1',
    `AI_LITE_OVERRIDE_USER_IDS=${overrideIds}`,
  );
  // Left unset by default so the CODE default is what gets measured and what the ledger records
  // - a stale pin here would silently benchmark a prompt the product no longer serves.
  if (PROMPT_VERSION) lines.push(`AI_LITE_PROMPT_VERSION=${PROMPT_VERSION}`);
} else {
  lines.push(
    '',
    '# Pro rides the general AI surface rather than a tier profile of its own: the routes are',
    '# pinned in code (PRO_STANDARD_ROUTES) and the bench passes them per run, so there is no',
    '# AI_PRO_* block to write. Lite is left OFF - enabling it here would change what the',
    '# wizard renders without changing anything the Pro bench measures.',
    'AI_LITE_ENABLED=0',
  );
}

if (carriedToken) lines.push('', carriedToken);
lines.push('');

writeFileSync(OUT, `${lines.join('\n')}\n`, 'utf8');
console.log(`wrote ${OUT} for the ${PROFILE} harness (${lines.length} lines, secrets copied not printed)`);
if (PROFILE === 'lite') {
  console.log(`  route ${MODEL} via vercel/vertex, ZDR required`);
  console.log(`  quota override for ${overrideIds}`);
  console.log(carriedToken ? '  carried the existing bearer token over' : '  no bearer token yet - run scripts/lite-eval-stamp.mjs');
} else {
  console.log('  gateway key + ZDR + the test account; routes come from the bench flags');
}
