// GUIDE.md — the modification walkthrough bundled into an OGraf STARTER package (ograf.html).
//
// The Yle ask behind the starters page (docs/GOALS.md "the SVG road"): organizations adopting
// OGraf want a BASE they modify, not from-scratch authoring — and a base is only a base if a
// newcomer can find where the data, the look and the motion live without reading the whole
// file. FIELDS.md already states the data contract; this guide is the map around it. It reads
// the template rather than asserting about it, so a starter whose shape changes updates its
// own guide on the next download.

import type { SpxTemplate } from '../model/types';

export function starterGuideMd(template: SpxTemplate): string {
  const fields = template.fields.filter((f) => f.ftype !== 'button');
  const fieldLines = fields
    .map((f) => `- \`${f.field}\` — ${f.title || f.field}${f.value ? ` (default: "${f.value}")` : ''}`)
    .join('\n');
  const rootVars = [...template.css.matchAll(/--[a-z0-9-]+(?=\s*:)/gi)]
    .map((m) => m[0])
    .filter((v, i, all) => all.indexOf(v) === i)
    .slice(0, 12);
  const hasAnim = template.js.includes('NOACG_ANIM');
  const sample = JSON.stringify(
    Object.fromEntries(fields.slice(0, 4).map((f) => [f.field, f.value || '…'])),
  );

  return `# ${template.name} — starter guide

A free OGraf v1 starter from NoaCG Studio (https://noacg.studio/ograf). It is meant to be
modified: this file says where everything lives. The package is validated against the EBU's
published OGraf schema before download, so what you are reading passed the same gate every
NoaCG export does.

## Load it

- Quick look: the community OGraf DevTool (https://ograf-devtool.superfly.tv) loads a package
  from your disk and gives you play/update/stop buttons and compliance checks.
- For real: any OGraf v1 renderer. The entry point is the \`*.ograf.json\` manifest; it names
  \`graphic.mjs\`, which default-exports the Graphic Web Component. Serve the folder over
  http(s) — browsers refuse ES module imports from \`file://\`.

## Drive it (the data)

The manifest's \`schema\` declares one property per operator field — the full table with types
and defaults is **FIELDS.md**. This graphic's fields:

${fieldLines || '- (this graphic has no operator fields)'}

Send data with \`updateAction\`:

\`\`\`json
{ "data": ${sample} }
\`\`\`

\`playAction\` plays the entrance and then steps forward; \`stopAction\` plays the exit. Data
never changes the graphic's state — that separation is part of the OGraf contract and of this
graphic's own design.

## Change the look

Open \`graphic.mjs\` and find the embedded CSS (\`TEMPLATE_CSS\`). The design reads its colors,
type and spacing from CSS custom properties declared in one rule (the studio's \`:root\` block,
re-addressed to the graphic's own element so it cannot restyle the renderer's page).
Restyle by changing those values, not by hunting through rules${rootVars.length ? `. This graphic's knobs include:

${rootVars.map((v) => `- \`${v}\``).join('\n')}` : '.'}

Fonts ship in \`fonts/\` with their licences beside them in \`fonts/FONT_LICENSES.md\`; \`@font-face\` rules in
the CSS point at them relatively, so a swapped font file is picked up as long as the name
matches.

## Change the motion

${hasAnim
    ? `The choreography is DATA, not scattered tween calls: find the \`NOACG_ANIM\` block in the
embedded template script. It declares keyframes per element for the entrance, each step and the
exit; durations and easings are plain values you can edit. The runtime that plays it is right
below the block, commented.`
    : `The choreography is hand-written GSAP in the embedded template script, commented inline —
edit the tweens directly.`}

## Remake it, or make it yours without code

This starter was generated by NoaCG Studio — the same graphic can be recolored, refonted and
re-animated in the browser (no code) and re-exported to OGraf, SPX, CasparCG, OBS or vMix:
https://noacg.studio/app

The spec, if you want the contract itself: https://ograf.ebu.io/
`;
}
