// Quiz scaffolding. Quiz graphics carry six FIXED data fields (they never come from
// o.lines — the wizard's line editor doesn't apply here):
//   f0 "Question" · f1–f4 "Answer A".."Answer D" · f5 "Correct answer" (dropdown A/B/C/D)
//
// Structure contract:
//   <div class="quiz">                 root — zone positioned; opacity:0 until play()
//     <div class="quiz-box">           the panel; presets tween this
//       <div class="quiz-mask"><span id="f0">…</span></div>      the question (mask-up reveal)
//       <div class="quiz-options">                               the four answer rows
//         <div class="quiz-option">
//           <span class="quiz-letter">A</span>                   static letter chip
//           <span id="f1">…</span>                             the answer text
//         </div>
//         …same for B/#f2, C/#f3, D/#f4…
//       </div>
//     </div>
//     hidden #f5 source SPX writes the correct letter into
//   </div>
//
// The reveal: SPX's Continue button calls next(), which reads the letter in #f5, marks
// that .quiz-option with 'quiz-correct' (accent treatment) and the other three with 'quiz-dim'
// (faded) — designs MUST style both classes. Presets tween .quiz-box and .quiz-option, so
// designs never put skew/rotation on those elements (paint it on ::before/::after layers).

import type { SpxField, SpxTemplate } from '../../model/types';
import { definitionScriptBlock } from '../../model/spxDefinition';
import { resolveEasing } from '../../model/easings';
import {
  resolveOptions,
  type ResolvedOptions,
  type TemplateVariant,
  type WizardOptions,
} from '../../model/wizard';
import {
  baseSettings,
  computeScale,
  documentHtml,
  maxTextWidthCss,
  resetCanvasCss,
  resolveHeadingFont,
  rootVarsCss,
  setFieldValueJs,
  zoneCssText,
} from '../shared/base';
import type { PresetConfig } from '../lowerThirds/animPresets';
import { quizPresetById } from './quizPresets';

export interface QuizDesign {
  /**
   * Inner HTML of .quiz — must contain .quiz-box with .quiz-mask > span#f0 and .quiz-options
   * holding the four .quiz-option rows (.quiz-letter chip + span#f1..#f4).
   */
  html: string;
  /**
   * Variant CSS (panel, question, option rows, letter chips). Colors via :root vars only.
   * MUST style .quiz-correct (accent treatment) and .quiz-dim (faded) for the reveal.
   */
  css: string;
  /** Whether the design includes a .quiz-accent element. */
  hasAccent: boolean;
}

export interface QuizMeta {
  name: string;
  description: string;
  /** SPX UI color label, "1".."7". */
  uicolor: string;
}

/** The six fixed quiz fields — every variant emits exactly these. */
const QUIZ_FIELDS: SpxField[] = [
  { field: 'f0', ftype: 'textfield', title: 'Question', value: 'Which planet is known as the Red Planet?' },
  { field: 'f1', ftype: 'textfield', title: 'Answer A', value: 'Venus' },
  { field: 'f2', ftype: 'textfield', title: 'Answer B', value: 'Mars' },
  { field: 'f3', ftype: 'textfield', title: 'Answer C', value: 'Pluto' },
  { field: 'f4', ftype: 'textfield', title: 'Answer D', value: 'Titan' },
  {
    field: 'f5',
    ftype: 'dropdown',
    title: 'Correct answer',
    value: 'B',
    items: [
      { text: 'A', value: 'A' },
      { text: 'B', value: 'B' },
      { text: 'C', value: 'C' },
      { text: 'D', value: 'D' },
    ],
  },
];

/** The quiz runtime: the standard scaffold plus the Continue-driven answer reveal. */
function quizRuntimeJs(name: string, animationBlock: string): string {
  return `// ${name} — generated by NoaCG Studio. SPX calls update(), play(), stop(), next().

// motionSpeed(): the template's speed knob. The NOACG_ANIM data block owns it; a legacy
// animSpeed variable is honored too, and hand-written animation code defaults to 1.
function motionSpeed() {
  if (typeof NOACG_ANIM !== 'undefined' && NOACG_ANIM.speed) return NOACG_ANIM.speed;
  if (typeof animSpeed !== 'undefined' && animSpeed) return animSpeed;
  return 1;
}

${setFieldValueJs}

// clearReveal(): remove a previous reveal so the graphic is back to the neutral state
// (fresh data, replay, or a second question all start un-revealed).
function clearReveal() {
  var options = document.querySelectorAll('.quiz-option');
  for (var i = 0; i < options.length; i++) {
    options[i].classList.remove('quiz-correct');
    options[i].classList.remove('quiz-dim');
  }
}

// update(data): SPX sends field values as JSON, e.g. {"f0":"…","f1":"Venus","f5":"B"}.
// Each value is written into the element whose id matches the field name (f0 -> id="f0");
// the correct letter (f5) lands in a hidden element that next() reads later.
function update(data) {
  var fields = (typeof data === 'string') ? JSON.parse(data) : data;
  for (var key in fields) {
    var el = document.getElementById(key);
    if (el) setFieldValue(el, fields[key]);
  }
  clearReveal();                   // new data means a new, not-yet-revealed question
}

// revealAnswer(): the money moment — read the correct letter from the hidden #f5,
// light that option up ('quiz-correct'), fade the other three ('quiz-dim'), and give the
// winner a small spring pop.
function revealAnswer() {
  var letter = document.getElementById('f5').textContent.trim().toUpperCase();
  var index = 'ABCD'.indexOf(letter);        // A -> row 0, B -> row 1, …
  var options = document.querySelectorAll('.quiz-option');
  if (index === -1 || !options[index]) return;  // unknown letter — do nothing
  clearReveal();                   // a second Continue press stays clean
  for (var i = 0; i < options.length; i++) {
    options[i].classList.add(i === index ? 'quiz-correct' : 'quiz-dim');
  }
  // Pop the correct row: enter slightly enlarged, spring back to rest.
  gsap.fromTo(options[index],
    { scale: 1.06 },
    { scale: 1, duration: 0.45 / motionSpeed(), ease: 'back.out(2)' }
  );
}

// play(): take the quiz on air — start un-revealed, run the entrance timeline.
function play() {
  gsap.killTweensOf('*');          // stop any animation that is still running
  clearReveal();                   // replays always start with the answer hidden
  buildInTimeline();
}

// stop(): take the quiz off air — run the exit timeline.
function stop() {
  gsap.killTweensOf('*');
  buildOutTimeline();
}

// next(): SPX Continue — step 2 of the graphic reveals the correct answer.
function next() {
  revealAnswer();
}

${animationBlock}
`;
}

/** Build the complete quiz SpxTemplate. */
export function assembleQuiz(meta: QuizMeta, design: QuizDesign, o: ResolvedOptions): SpxTemplate {
  const font = resolveHeadingFont(o); // imported font wins over the bundled set
  const scale = computeScale(o);
  // A question plus four answer rows reads best a bit wider than a single strap.
  const maxTextWidth = Math.round(o.resolution.width * 0.48);

  // steps '2': phase 1 = question + options in, phase 2 (Continue) = answer reveal.
  const settings = baseSettings(meta, o, { steps: '2' });

  const html = documentHtml({
    title: meta.name,
    definitionBlock: definitionScriptBlock(settings, QUIZ_FIELDS),
    body: `  <!-- Quiz root — the question, four answer rows, and the hidden correct letter. -->
  <div class="quiz">
${design.html}
    <!-- Hidden correct-answer source — SPX writes field f5 here; next() reads it. -->
    <div id="f5" style="display: none">B</div>
  </div>`,
  });

  const css = `/* ${meta.name} — generated by NoaCG Studio. Edit freely: this file is yours. */

${rootVarsCss(o, font.stack, scale)}

${font.face}

${resetCanvasCss(o.resolution)}

/* ── Root position (anchor zone) ── */
.quiz {
  position: absolute;
${zoneCssText(o.zone, o.nudge, o.resolution)}
  opacity: 0;                      /* hidden until play() runs the entrance */
}

/* ── Auto-fit: the panel hugs its content and wraps instead of overflowing. ── */
.quiz-box {
  width: fit-content;              /* the panel hugs the question and answers */
  max-width: ${maxTextWidthCss(o.resolution, maxTextWidth)};  /* the wrap cap — follows --scale, stops at the safe area */
  will-change: transform, opacity; /* hint the browser: this element animates */
}
.quiz-mask {
  overflow: hidden;                /* the question animates in from behind this mask */
}
.quiz-mask > span {
  display: inline-block;           /* so the question can move inside its mask */
  overflow-wrap: break-word;       /* break very long unbroken words */
  text-wrap: balance;              /* wrapped rows get even lengths */
}
.quiz-option {
  will-change: transform, opacity; /* the rows stagger in and pop on reveal */
}

/* ── Design ── */
${design.css}
`;

  const preset = quizPresetById(o.animation.presetId);
  // 'auto' uses the preset's hand-tuned ease pair; a named easing preset overrides both phases.
  const ease = resolveEasing(o.animation.easing, preset.autoEase);
  const cfg: PresetConfig = {
    prefix: 'quiz',
    lineCount: 5, // f0 question · f1–f4 answers (f5 is the hidden correct letter)
    hasAccent: design.hasAccent,
    steps: false, // the reveal is the second step — handled by next(), not the preset
    speed: o.animation.speed,
    easeIn: ease.easeIn,
    easeOut: ease.easeOut,
  };

  const js = quizRuntimeJs(meta.name, preset.emit(cfg));

  return {
    name: meta.name,
    type: 'quiz',
    resolution: o.resolution,
    fps: o.fps,
    html,
    css,
    js,
    fields: QUIZ_FIELDS,
    settings,
    assets: [...o.importedImages, ...(o.customFont ? [o.customFont.asset] : [])],
    layers: QUIZ_FIELDS.filter((f) => f.ftype === 'textfield').map((f) => ({
      id: f.field,
      type: 'text' as const,
      label: f.title,
      fieldId: f.field,
      text: f.value,
      styles: {},
    })),
  };
}

/** The authoring API for quiz variant modules. */
export function defineQuizVariant(
  spec: Omit<TemplateVariant, 'create'>,
  meta: QuizMeta,
  buildDesign: (o: ResolvedOptions) => QuizDesign,
): TemplateVariant {
  const variant: TemplateVariant = {
    ...spec,
    create(options?: WizardOptions) {
      const o = resolveOptions(variant, options);
      return assembleQuiz(meta, buildDesign(o), o);
    },
  };
  return variant;
}
