// Starting-soon scaffolding. A pre-show holding screen: a big title (f0), the show name
// (f1), and a countdown clock driven by the shared clock runtime (templates/shared/clock.ts).
// The duration lives in a hidden #f2 field (whole minutes; "0.5" = 30 s) — the .starting-soon-clock
// element is painted by JS every second, it is NOT a data field.
//
// Structure contract:
//   <div class="starting-soon">                  root — positioned by zone; opacity:0 until play()
//     <div class="starting-soon-box">            the panel; presets fade + raise this
//       .starting-soon-mask > #f0 / #f1 spans    title + show name (mask-wrapped, auto-fit)
//       <div class="starting-soon-clock">        JS paints M:SS here (clockRuntimeJs)
//       one element with class "starting-soon-pulse"   the hold-loop preset breathes it
//     </div>
//     hidden #f2 source SPX writes the minutes into
//   </div>

import type { SpxField, SpxTemplate } from '../../model/types';
import { definitionScriptBlock } from '../../model/spxDefinition';
import { resolveEasing } from '../../model/easings';
import {
  resolveOptions,
  type ResolvedOptions,
  type TemplateVariant,
  type WizardOptions,
} from '../../model/wizard';
import {
  baseSettings,
  computeScale,
  documentHtml,
  maxTextWidthCss,
  resetCanvasCss,
  resolveHeadingFont,
  rootVarsCss,
  setFieldValueJs,
  zoneCssText,
} from '../shared/base';
import { clockRuntimeJs } from '../shared/clock';
import type { AnimData } from '../../blocks/animData';
import { convertToDataRegion } from '../shared/standard';
import type { PresetConfig } from '../lowerThirds/animPresets';
import { ssPresetById } from './ssPresets';
import { resolveTokens, type ThemeTokens, type TokenOverrides } from '../../model/themeTokens';

export interface StartingSoonDesign {
  /**
   * Inner HTML of .starting-soon — must contain .starting-soon-box with mask-wrapped #f0 and #f1 spans,
   * a .starting-soon-clock element, and exactly one element carrying class "starting-soon-pulse".
   */
  html: string;
  /** Variant CSS (panel, title, show name, clock, pulse; done-state via .starting-soon-done). */
  css: string;
  /**
   * Where this design disagrees with its style family's shape tokens
   * (model/themeTokens.ts). Every entry is conformance debt - DESIGN_LANGUAGE §8's rule is
   * "reuse the exact token values, don't improvise new ones per category".
   */
  tokens?: TokenOverrides;
}

export interface StartingSoonMeta {
  name: string;
  description: string;
  uicolor: string;
}

/** The shared runtime: field updates + the countdown clock (outside the markers). */
function ssRuntimeJs(name: string, animationBlock: string): string {
  return `// ${name} — generated by NoaCG Studio. SPX calls update(), play(), stop(), next().

${clockRuntimeJs('starting-soon', 'f2')}

${setFieldValueJs}

// update(data): SPX sends field values as JSON; each value is written into the element
// whose id matches the field name (f2 is the hidden minutes source the clock reads).
function update(data) {
  var fields = (typeof data === 'string') ? JSON.parse(data) : data;
  for (var key in fields) {
    var el = document.getElementById(key);
    if (el) setFieldValue(el, fields[key]);
  }
  // If the countdown isn't running yet, repaint the idle clock with the new duration.
  if (!clockTimer) {
    clockSecondsLeft = clockDurationSeconds();
    renderClock();
  }
}

// play(): take the holding screen on air — the entrance also starts the countdown.
function play() {
  gsap.killTweensOf('*');          // stop any animation that is still running
  buildInTimeline();
}

// stop(): take the screen off air (the exit also stops the countdown).
function stop() {
  gsap.killTweensOf('*');
  buildOutTimeline();
}

// next(): SPX Continue — advance one step along the default path. This design ships
// single-step, so it normally does nothing; it still funnels to the interpreter so a
// template that GROWS a step (or a state machine) stays drivable through the SPX contract.
function next() {
  return (typeof revealNextStep === 'function') ? revealNextStep() : null;
}

${animationBlock}
`;
}

/** Build the complete starting-soon SpxTemplate. */
export function assembleStartingSoon(
  meta: StartingSoonMeta,
  design: StartingSoonDesign,
  o: ResolvedOptions,
  /** Refine the converted animation data — the seam a graphic TYPE injects its machine
   *  through (see shared/standard.ts composeRefine for the ordering rule). */
  refine?: (data: AnimData) => AnimData,
  /** The design's resolved SHAPE tokens (model/themeTokens.ts). Resolved by the caller,
   *  because the family lives on the VARIANT (styleTag) and this function only sees the
   *  design. Absent = emit no token lines, which is what every template did before they
   *  existed. */
  tokens?: ThemeTokens,
): SpxTemplate {
  const font = resolveHeadingFont(o);
  const scale = computeScale(o);
  // Holding screens are the show's front door: wider cap than a strap (~70% of the canvas).
  const maxTextWidth = Math.round(o.resolution.width * 0.7);

  const titleText = o.lines[0]?.sample || 'STARTING SOON';
  const showText = o.lines[1]?.sample || 'The Evening Show';
  const fields: SpxField[] = [
    { field: 'f0', ftype: 'textfield', title: o.lines[0]?.title || 'Title', value: titleText },
    { field: 'f1', ftype: 'textfield', title: o.lines[1]?.title || 'Show name', value: showText },
    { field: 'f2', ftype: 'textfield', title: 'Countdown (minutes)', value: '5' },
  ];

  const settings = baseSettings(meta, o, { steps: '1', playlayer: '4', webplayout: '4' });

  const html = documentHtml({
    title: meta.name,
    definitionBlock: definitionScriptBlock(settings, fields),
    body: `  <!-- ${meta.name}. The clock (M:SS) is painted by JS from the hidden minutes source below. -->
  <div class="starting-soon">
${design.html}
    <!-- Hidden countdown source — SPX writes field f2 (minutes) here; the clock reads it. -->
    <div id="f2" style="display: none">5</div>
  </div>`,
  });

  const css = `/* ${meta.name} — generated by NoaCG Studio. Edit freely: this file is yours. */

${rootVarsCss(o, font.stack, scale, { tokens, consumerCss: design.css })}

${font.face}

${resetCanvasCss(o.resolution)}

/* ── Root position (anchor zone) ── */
.starting-soon {
  position: absolute;
${zoneCssText(o.zone, o.nudge, o.resolution)}
  opacity: 0;                      /* hidden until play() runs the entrance */
}

/* ── Auto-fit: the panel hugs its text and wraps instead of overflowing. ── */
.starting-soon-box {
  width: fit-content;              /* the panel hugs the text */
  max-width: ${maxTextWidthCss(o.resolution, maxTextWidth)};  /* the wrap cap — follows --scale, stops at the safe area */
  will-change: transform, opacity; /* hint the browser: this element animates */
}
.starting-soon-mask {
  overflow: hidden;                /* lines animate in from behind this mask */
}
.starting-soon-mask > span {
  display: inline-block;           /* so the line can move inside its mask */
  overflow-wrap: break-word;       /* break very long unbroken words */
  text-wrap: balance;              /* wrapped rows get even lengths */
}

/* ── Design ── */
${design.css}
`;

  const preset = ssPresetById(o.animation.presetId);
  const ease = resolveEasing(o.animation.easing, preset.autoEase);
  const cfg: PresetConfig = {
    prefix: 'starting-soon',
    lineCount: 2,
    hasAccent: false,
    steps: false,
    speed: o.animation.speed,
    easeIn: ease.easeIn,
    easeOut: ease.easeOut,
  };

  const js = ssRuntimeJs(meta.name, preset.emit(cfg));

  const template: SpxTemplate = {
    name: meta.name,
    type: 'starting-soon',
    resolution: o.resolution,
    fps: o.fps,
    html,
    css,
    js,
    fields,
    settings,
    assets: [...o.importedImages, ...(o.customFont ? [o.customFont.asset] : [])],
    layers: [],
  };

  // Timeline v2: convert the marked region into the NOACG_ANIM data block + interpreter.
  // The ambient breath is now describable as data (a looping scale track — gap 6), and the
  // step-calls model (§3b) carries startClock()/stopClock(), so the hold loop and countdown
  // both survive the flip; the clock runtime lives OUTSIDE the region and is untouched. A
  // conversion failure keeps the legacy emit — never a broken template.
  return convertToDataRegion(template, refine);
}

/** The authoring API for starting-soon variant modules. */
export function defineStartingSoonVariant(
  spec: Omit<TemplateVariant, 'create'>,
  meta: StartingSoonMeta,
  buildDesign: (o: ResolvedOptions) => StartingSoonDesign,
  /** Optional animation-data refinement (a graphic type's machine rides in here). It is
   *  built per create() because a type's compiled machine depends on the resolved options. */
  refine?: (o: ResolvedOptions) => ((data: AnimData) => AnimData) | undefined,
): TemplateVariant {
  const variant: TemplateVariant = {
    ...spec,
    create(options?: WizardOptions) {
      const o = resolveOptions(variant, options);
      const design = buildDesign(o);
      // The family lives on the variant, the overrides on the design — resolved here
      // because this is the only place that holds both.
      const tokens = resolveTokens(spec.styleTag, design.tokens);
      return assembleStartingSoon(meta, design, o, refine?.(o), tokens);
    },
  };
  return variant;
}
