// Scoreboard scaffolding. Scoreboards carry four FIXED data fields (they never come from
// o.lines — the wizard's line editor doesn't apply here):
//   f0 "Team A" (name) · f1 "Score A" · f2 "Team B" (name) · f3 "Score B"
//
// Structure contract (mirrors the standard .lower-third contract so the six standard lowerThirds
// animation presets work unchanged with prefix 'scoreboard' and lineCount 4):
//   <div class="scoreboard">                 root — zone positioned; opacity:0 until play()
//     <div class="scoreboard-box">           the panel; presets tween this
//       team group A:
//         <div class="scoreboard-mask"><span id="f0" class="scoreboard-team">HOME</span></div>
//         <div class="scoreboard-mask"><span id="f1" class="scoreboard-score">0</span></div>
//       …divider of the design's choice…
//       team group B:
//         <div class="scoreboard-mask"><span id="f2" class="scoreboard-team">AWAY</span></div>
//         <div class="scoreboard-mask"><span id="f3" class="scoreboard-score">0</span></div>
//     </div>
//   </div>
//
// The runtime adds a score-pop: while the graphic is on air, a score value (f1/f3) that
// actually changes scales up briefly and springs back — the classic broadcast score bump.

import type { SpxField, SpxTemplate } from '../../model/types';
import { definitionScriptBlock } from '../../model/spxDefinition';
import { resolveEasing } from '../../model/easings';
import {
  resolveOptions,
  type ResolvedOptions,
  type TemplateVariant,
  type WizardOptions,
} from '../../model/wizard';
import {
  baseSettings,
  computeScale,
  documentHtml,
  resetCanvasCss,
  resolveHeadingFont,
  rootVarsCss,
  setFieldValueJs,
  zoneCssText,
} from '../shared/base';
import { presetById, type PresetConfig } from '../lowerThirds/animPresets';

export interface SbDesign {
  /** Inner HTML of .scoreboard — must contain .scoreboard-box with the four .scoreboard-mask > span#fN lines. */
  html: string;
  /** Variant CSS (panel, team names, scores, divider). Colors via :root vars only. */
  css: string;
  /** Whether the design includes a .scoreboard-accent element (line-reveal draws it first). */
  hasAccent: boolean;
}

export interface SbMeta {
  name: string;
  description: string;
  /** SPX UI color label, "1".."7". */
  uicolor: string;
}

/** The four fixed scoreboard fields — every variant emits exactly these. */
const SB_FIELDS: SpxField[] = [
  { field: 'f0', ftype: 'textfield', title: 'Team A', value: 'HOME' },
  { field: 'f1', ftype: 'textfield', title: 'Score A', value: '0' },
  { field: 'f2', ftype: 'textfield', title: 'Team B', value: 'AWAY' },
  { field: 'f3', ftype: 'textfield', title: 'Score B', value: '0' },
];

/** The scoreboard runtime: the standard scaffold plus an on-air score-pop in update(). */
function sbRuntimeJs(name: string, animationBlock: string): string {
  return `// ${name} — generated by NoaCG Studio. SPX calls update(), play(), stop(), next().

var onAir = false;               // true between play() and stop() — pops only happen on air
var scoreIds = ['f1', 'f3'];     // the two score fields (f0/f2 are the team names)

${setFieldValueJs}

// update(data): SPX sends field values as JSON, e.g. {"f0":"HOME","f1":"2"}.
// Each value is written into the element whose id matches the field name (f0 -> id="f0").
// A score that CHANGES while on air gets a pop: scale up, then spring back down.
function update(data) {
  var fields = (typeof data === 'string') ? JSON.parse(data) : data;
  for (var key in fields) {
    var el = document.getElementById(key);
    if (!el) continue;
    var changed = el.textContent !== String(fields[key]);  // textContent: exactly what the operator typed
    setFieldValue(el, fields[key]);
    if (changed && onAir && scoreIds.indexOf(key) !== -1) {
      // Pop the MASK (the span's parent), not the span: the span is clipped by the mask's
      // overflow:hidden, so scaling it would chop the outer digits of a two-digit score.
      // Scaling the mask scales its clip region together with the digits — nothing is cut.
      // No preset ever tweens a mask, so the pop can't collide with an entrance or exit.
      gsap.fromTo(el.parentNode,
        { scale: 1.35 },
        { scale: 1, duration: 0.4 / animSpeed, ease: 'back.out(1.7)' }
      );
    }
  }
}

// play(): take the scoreboard on air — run the entrance timeline.
function play() {
  gsap.killTweensOf('*');          // stop any animation that is still running
  resetScorePop();                 // a killed mid-pop score must not enter enlarged
  onAir = true;
  buildInTimeline();
}

// stop(): take the scoreboard off air — run the exit timeline.
function stop() {
  gsap.killTweensOf('*');
  resetScorePop();                 // don't freeze a half-finished pop at scale > 1
  onAir = false;
  buildOutTimeline();
}

// resetScorePop(): killTweensOf() can freeze a score mid-pop at scale ~1.x; the
// entrance/exit timelines never touch the masks, so snap both score masks back to 1 here.
function resetScorePop() {
  for (var i = 0; i < scoreIds.length; i++) {
    var el = document.getElementById(scoreIds[i]);
    if (el) gsap.set(el.parentNode, { scale: 1 });  // the mask is what update() pops
  }
}

// next(): scoreboards have no steps.
function next() {}

${animationBlock}
`;
}

/** Build the complete scoreboard SpxTemplate. */
export function assembleScoreboard(meta: SbMeta, design: SbDesign, o: ResolvedOptions): SpxTemplate {
  const font = resolveHeadingFont(o); // imported font wins over the bundled set
  const scale = computeScale(o);
  // Scoreboards span two team groups side by side — cap wider than a single strap.
  const maxTextWidth = Math.round(o.resolution.width * 0.6);

  const settings = baseSettings(meta, o, { steps: '1' }); // scoreboards have no steps

  const html = documentHtml({
    title: meta.name,
    definitionBlock: definitionScriptBlock(settings, SB_FIELDS),
    body: `  <!-- Scoreboard root — two team groups (name + score) inside one panel. -->
  <div class="scoreboard">
${design.html}
  </div>`,
  });

  const css = `/* ${meta.name} — generated by NoaCG Studio. Edit freely: this file is yours. */

${rootVarsCss(o, font.stack, scale)}

${font.face}

${resetCanvasCss(o.resolution)}

/* ── Root position (anchor zone) ── */
.scoreboard {
  position: absolute;
${zoneCssText(o.zone, o.nudge, o.resolution)}
  opacity: 0;                      /* hidden until play() runs the entrance */
}

/* ── Auto-fit: the panel hugs its content and wraps instead of overflowing. ── */
.scoreboard-box {
  width: fit-content;              /* the panel hugs the two team groups */
  max-width: ${maxTextWidth}px;             /* never wider than this — text wraps instead */
  will-change: transform, opacity; /* hint the browser: this element animates */
}
.scoreboard-mask {
  overflow: hidden;                /* lines animate in from behind this mask */
}
.scoreboard-mask > span {
  display: inline-block;           /* so the line can move (and pop) inside its mask */
  overflow-wrap: break-word;       /* break very long unbroken team names */
  text-wrap: balance;              /* wrapped rows get even lengths */
}

/* ── Design ── */
${design.css}
`;

  const preset = presetById(o.animation.presetId);
  // 'auto' uses the preset's hand-tuned ease pair; a named easing preset overrides both phases.
  const ease = resolveEasing(o.animation.easing, preset.autoEase);
  const cfg: PresetConfig = {
    prefix: 'scoreboard',
    lineCount: 4, // f0 team A · f1 score A · f2 team B · f3 score B
    hasAccent: design.hasAccent,
    steps: false, // scoreboards never step — the whole board enters at once
    speed: o.animation.speed,
    easeIn: ease.easeIn,
    easeOut: ease.easeOut,
  };

  const js = sbRuntimeJs(meta.name, preset.emit(cfg));

  return {
    name: meta.name,
    type: 'scoreboard',
    resolution: o.resolution,
    fps: o.fps,
    html,
    css,
    js,
    fields: SB_FIELDS,
    settings,
    assets: [...o.importedImages, ...(o.customFont ? [o.customFont.asset] : [])],
    layers: SB_FIELDS.map((f) => ({
      id: f.field,
      type: 'text' as const,
      label: f.title,
      fieldId: f.field,
      text: f.value,
      styles: {},
    })),
  };
}

/** The authoring API for scoreboard variant modules. */
export function defineScoreboardVariant(
  spec: Omit<TemplateVariant, 'create'>,
  meta: SbMeta,
  buildDesign: (o: ResolvedOptions) => SbDesign,
): TemplateVariant {
  const variant: TemplateVariant = {
    ...spec,
    create(options?: WizardOptions) {
      const o = resolveOptions(variant, options);
      return assembleScoreboard(meta, buildDesign(o), o);
    },
  };
  return variant;
}
