// PreToolUse guard for the file-editing tools (Edit / Write / notebook edits): blocks edits
// to files that must never be hand-modified, with a pointer to the right way to change each.

import { relative, resolve } from 'node:path';
import { readHookInput, deny } from './lib.mjs';

const input = await readHookInput();
const filePath = input?.tool_input?.file_path ?? input?.tool_input?.notebook_path;
if (typeof filePath !== 'string' || filePath.length === 0) process.exit(0);

const abs = resolve(filePath).replaceAll('\\', '/');

// Generated per-checkout by postinstall - never hand-edited, in ANY checkout (CLAUDE.md).
if (abs.endsWith('/.claude/launch.json')) {
  deny(
    '.claude/launch.json is generated by postinstall (scripts/dev-port.mjs) and must never be ' +
      'hand-edited. Run `node scripts/dev-port.mjs` to regenerate it; to change what it contains, ' +
      'edit writeLaunchConfig() in scripts/dev-port.mjs.',
  );
}

// The published record of this checkout's reserved port - a mirror of the registry ticket,
// rewritten on every resolution. Editing it changes nothing and desyncs the tooling.
if (abs.endsWith('/.claude/dev-port.json')) {
  deny(
    '.claude/dev-port.json is generated by scripts/dev-port.mjs - it reports the port this ' +
      'checkout reserved, it does not decide it (docs/DEV_PORTS.md). To move this checkout to ' +
      'another port, run `node scripts/dev-port.mjs --release` and let it re-allocate.',
  );
}

// The remaining rules are repo-relative; files outside this checkout are not ours to police.
const rel = relative(process.cwd(), abs).replaceAll('\\', '/');
if (rel.startsWith('..')) process.exit(0);

if (rel.startsWith('dist/')) {
  deny('dist/ is build output - edit the source instead and rebuild with `npm run build`.');
}

if (rel === 'src/assets/gsap.min.js') {
  deny(
    'src/assets/gsap.min.js is the vendored GSAP bundle - not ours to modify (offline-first rule ' +
      'in CLAUDE.md). If a different GSAP build is needed, replace the file wholesale from an ' +
      'official release, with the user\'s sign-off.',
  );
}

if (rel === 'package-lock.json') {
  deny(
    'package-lock.json should only change through npm (npm install / update / dedupe), never a ' +
      'direct edit. Run the npm command that produces the change instead.',
  );
}

process.exit(0);
